/* ============================================================
   AVANZADO: OOP, decoradores, generadores, context managers,
   type hints y proyecto integrador
   ============================================================ */
DOJO_PUSH("avanzado", [

/* ---------------- OOP ---------------- */
{
  id: "oop",
  title: "Programación orientada a objetos",
  intro: "Hasta ahora: datos por un lado (dicts, listas), funciones por el otro. Una <strong>clase</strong> los une: estado + comportamiento en una sola pieza con nombre. Es el vocabulario de todos los frameworks que vas a usar — incluido scikit-learn, donde cada modelo es un objeto.",
  socratic: [
    {
      q: "Podrías representar una cuenta bancaria con un dict <code>{\"owner\": ..., \"balance\": ...}</code> y funciones sueltas <code>deposit(cuenta, monto)</code>. ¿Qué problema tiene eso que la clase resuelve?",
      a: "Nada impide que cualquier código haga <code>cuenta[\"balance\"] = -999999</code> directamente, salteando tus validaciones. El dict es datos desnudos: las reglas viven lejos, en funciones que <em>ojalá</em> todos usen. La clase junta datos y reglas en una unidad: el balance se toca a través de métodos que validan. Eso es <strong>encapsulamiento</strong> — el objeto defiende sus propios invariantes."
    },
    {
      q: "En <code>def deposit(self, amount):</code> — ¿qué es exactamente <code>self</code> y por qué al llamar <code>account.deposit(100)</code> no se lo pasás?",
      a: "<code>self</code> ES el objeto sobre el que se llamó el método. <code>account.deposit(100)</code> es azúcar sintáctico de <code>BankAccount.deposit(account, 100)</code>: Python pasa el objeto como primer argumento automáticamente. Por eso todo método lo declara: es el puente para que el método lea y modifique LOS datos de ESE objeto (<code>self.balance</code>) y no los de otro."
    },
    {
      q: "¿Qué es <code>__init__</code> y cuándo corre? ¿Y por qué los atributos se crean ahí y no sueltos en la clase?",
      a: "Es el inicializador: corre automáticamente al crear cada objeto (<code>BankAccount(\"ana\", 100)</code>), y su trabajo es dejar al objeto en un estado válido desde el primer segundo. Los atributos se crean ahí con <code>self.x = ...</code> porque cada objeto necesita SU copia: un atributo definido suelto en la clase es compartido por todas las instancias — fuente de bugs legendarios con listas compartidas."
    },
    {
      q: "Herencia: <code>class Dog(Animal)</code>. ¿Qué significa, y qué hace <code>super().__init__(...)</code>?",
      a: "Dog ES UN Animal: hereda todos sus métodos y atributos gratis, y puede agregar propios o <strong>redefinir</strong> (override) los que necesite distintos. <code>super().__init__(name)</code> llama al inicializador del padre — porque al redefinir __init__ en el hijo, el del padre ya no corre solo, y alguien tiene que crear los atributos que el padre prometía. Regla: el hijo extiende, no repite — lo común vive una sola vez, arriba."
    },
    {
      q: "Polimorfismo: una función recorre una lista de figuras llamando <code>shape.area()</code> sin saber si cada una es círculo o rectángulo. ¿Por qué eso es poderoso?",
      a: "Porque el código que USA las figuras no cambia cuando agregás figuras nuevas: mañana creás Triangle con su .area() y la función de totales la procesa sin enterarse. Cada objeto responde al mismo mensaje a su manera. En Python ni siquiera hace falta herencia común — alcanza con que respondan al método (<em>duck typing</em>: si camina como pato y hace cuac…). Así scikit-learn entrena CUALQUIER modelo: todos responden a .fit() y .predict()."
    }
  ],
  exercises: [
    {
      id: "adv-oop-1",
      title: "Tu primera clase",
      difficulty: 1,
      prompt: "<p>Creá la clase <code>Dog</code>:</p><ul><li><code>__init__(self, name)</code>: guarda el nombre en <code>self.name</code>.</li><li><code>bark(self)</code>: devuelve <code>\"Rex says woof!\"</code> (con el nombre del perro en cuestión).</li></ul><p>Después instanciá dos perros distintos — <code>rex = Dog(\"Rex\")</code> y <code>luna = Dog(\"Luna\")</code> — para comprobar que cada uno conoce SU nombre.</p>",
      starter: "class Dog:\n    # __init__ y bark\n    pass\n\n# rex = ?\n# luna = ?\n",
      tests: "assert rex.name == \"Rex\", f\"rex.name: {rex.name}\"\nassert luna.name == \"Luna\", f\"luna.name: {luna.name}\"\nassert rex.bark() == \"Rex says woof!\", f\"rex.bark(): {rex.bark()}\"\nassert luna.bark() == \"Luna says woof!\", f\"luna.bark(): {luna.bark()}\"\nassert type(rex) is Dog, \"rex tiene que ser una instancia de Dog\"",
      solution: "class Dog:\n    def __init__(self, name):\n        self.name = name\n\n    def bark(self):\n        return f\"{self.name} says woof!\"\n\nrex = Dog(\"Rex\")\nluna = Dog(\"Luna\")",
      explanation: "<p>La clase es el <strong>molde</strong>; <code>rex</code> y <code>luna</code> son objetos salidos de él, cada uno con su propio <code>name</code>. Seguí el viaje de \"Rex\": <code>Dog(\"Rex\")</code> dispara <code>__init__</code> con <code>self</code> = el objeto recién nacido y <code>name</code> = \"Rex\"; <code>self.name = name</code> lo guarda EN el objeto. Cuando después llamás <code>rex.bark()</code>, el <code>self.name</code> del método encuentra el \"Rex\" guardado.</p><p>La prueba de fuego conceptual es que <code>luna.bark()</code> dice Luna: mismo método, código escrito una sola vez, pero <code>self</code> es otro objeto con otros datos. Estado propio + comportamiento compartido — eso es una clase.</p>",
      hints: ["def __init__(self, name): / self.name = name — el self adelante es lo que hace que cada perro tenga el suyo.", "bark usa self.name: return f\"{self.name} says woof!\". Instanciar: rex = Dog(\"Rex\")."]
    },
    {
      id: "adv-oop-2",
      title: "Estado protegido: la cuenta bancaria",
      difficulty: 2,
      prompt: "<p>Creá <code>BankAccount</code>:</p><ul><li><code>__init__(self, owner, balance=0)</code></li><li><code>deposit(self, amount)</code>: suma al balance; montos no positivos → <code>raise ValueError(\"monto invalido\")</code>.</li><li><code>withdraw(self, amount)</code>: resta; montos no positivos → <code>ValueError</code>; si supera el balance → <code>raise ValueError(\"fondos insuficientes\")</code>.</li><li>Ambos devuelven el balance resultante.</li></ul><p>Las guard clauses que aprendiste en errores, ahora defendiendo el estado del objeto.</p>",
      starter: "class BankAccount:\n    pass\n\n# proba mientras desarrollas:\n# acc = BankAccount(\"ana\", 100)\n# print(acc.deposit(50))\n# print(acc.withdraw(30))\n",
      tests: "acc = BankAccount(\"ana\", 100)\nassert acc.owner == \"ana\" and acc.balance == 100\nassert acc.deposit(50) == 150, \"deposit deberia devolver el balance nuevo\"\nassert acc.balance == 150\nassert acc.withdraw(70) == 80\nacc2 = BankAccount(\"beto\")\nassert acc2.balance == 0, \"el balance por defecto es 0\"\ntry:\n    acc.withdraw(99999)\n    assert False, \"retirar mas que el balance deberia tirar ValueError\"\nexcept ValueError:\n    pass\nassert acc.balance == 80, \"un retiro fallido NO debe tocar el balance\"\ntry:\n    acc.deposit(-5)\n    assert False, \"depositar negativo deberia tirar ValueError\"\nexcept ValueError:\n    pass",
      solution: "class BankAccount:\n    def __init__(self, owner, balance=0):\n        self.owner = owner\n        self.balance = balance\n\n    def deposit(self, amount):\n        if amount <= 0:\n            raise ValueError(\"monto invalido\")\n        self.balance += amount\n        return self.balance\n\n    def withdraw(self, amount):\n        if amount <= 0:\n            raise ValueError(\"monto invalido\")\n        if amount > self.balance:\n            raise ValueError(\"fondos insuficientes\")\n        self.balance -= amount\n        return self.balance",
      explanation: "<p>El test más importante es el menos visible: tras el retiro fallido, <code>acc.balance</code> seguía en 80. Las guard clauses van ANTES de tocar el estado — si algo está mal, el objeto queda exactamente como estaba. Esa propiedad (\"o la operación completa, o nada\") se llama atomicidad, y es la diferencia entre un sistema confiable y uno que se corrompe de a poco.</p><p>Esto es encapsulamiento en acción: el balance solo se mueve por las puertas oficiales que validan. (Confesión: en Python nada impide técnicamente <code>acc.balance = -1</code> desde afuera — la convención del lenguaje es \"somos todos adultos\", y para protección más seria existen <code>@property</code> y el prefijo <code>_privado</code>. Pero el diseño correcto es este: las reglas viven con los datos.)</p>",
      hints: ["__init__ con default: def __init__(self, owner, balance=0).", "Cada método: primero las guard clauses con raise, después tocar self.balance, al final return self.balance.", "¿Falla el test del retiro fallido? Estás modificando el balance antes de validar."]
    },
    {
      id: "adv-oop-3",
      title: "__str__ y __repr__: objetos que se presentan",
      difficulty: 3,
      prompt: "<p>Creá la clase <code>Book</code> con <code>__init__(self, title, author, year)</code> y dos métodos mágicos:</p><ul><li><code>__str__(self)</code> → <code>\"Dune by Frank Herbert (1965)\"</code> — la versión para humanos: es lo que muestra <code>print(book)</code> y <code>str(book)</code>.</li><li><code>__repr__(self)</code> → <code>\"Book('Dune', 'Frank Herbert', 1965)\"</code> — la versión para programadores: idealmente, código Python que recrearía el objeto.</li></ul><p>Probá <code>print(book)</code> y <code>print([book])</code> — ¿cuál usa cada uno? (Sorpresa: las listas muestran el repr de sus elementos.)</p>",
      starter: "class Book:\n    pass\n\nbook = Book(\"Dune\", \"Frank Herbert\", 1965)\nprint(book)      # usa __str__\nprint([book])    # usa __repr__ !\n",
      tests: "book = Book(\"Dune\", \"Frank Herbert\", 1965)\nassert str(book) == \"Dune by Frank Herbert (1965)\", f\"__str__: {str(book)}\"\nassert repr(book) == \"Book('Dune', 'Frank Herbert', 1965)\", f\"__repr__: {repr(book)}\"\nb2 = Book(\"Neuromancer\", \"William Gibson\", 1984)\nassert str(b2) == \"Neuromancer by William Gibson (1984)\", \"tiene que funcionar para cualquier libro\"",
      solution: "class Book:\n    def __init__(self, title, author, year):\n        self.title = title\n        self.author = author\n        self.year = year\n\n    def __str__(self):\n        return f\"{self.title} by {self.author} ({self.year})\"\n\n    def __repr__(self):\n        return f\"Book({self.title!r}, {self.author!r}, {self.year!r})\"",
      explanation: "<p>Los métodos <code>__asi__</code> (\"dunder\") son los enchufes con que tus objetos se conectan a la maquinaria de Python: definí <code>__str__</code> y <code>print()</code> lo usa; definí <code>__len__</code> y <code>len()</code> funciona; <code>__eq__</code> y el <code>==</code> compara como vos digas. No llamás a estos métodos — Python los llama por vos. Es el mismo mecanismo por el que <code>date - date</code> funcionaba en Intermedio.</p><p>La división de audiencias: <code>__str__</code> para el usuario final (legible), <code>__repr__</code> para vos depurando (preciso, sin ambigüedad — por eso las comillas en los strings: distinguen <code>Book('1984', ...)</code> de <code>Book(1984, ...)</code>). El <code>!r</code> en el f-string pide el repr de cada campo, que pone esas comillas solo. Si definís uno solo, que sea <code>__repr__</code>: actúa de respaldo para ambos.</p>",
      hints: ["Son métodos comunes con nombre especial: def __str__(self): return f\"...\".", "Para el repr con comillas correctas: f\"Book({self.title!r}, {self.author!r}, {self.year!r})\" — el !r es la clave."]
    },
    {
      id: "adv-oop-4",
      title: "Herencia: la familia Animal",
      difficulty: 4,
      prompt: "<p>Construí la jerarquía:</p><ul><li><code>Animal</code>: <code>__init__(self, name, sound)</code> guarda ambos; <code>speak(self)</code> → <code>\"Rex says guau\"</code>; <code>eat(self)</code> → <code>\"Rex is eating\"</code>.</li><li><code>Dog(Animal)</code>: su <code>__init__</code> recibe SOLO <code>name</code> y llama a <code>super().__init__(name, \"guau\")</code>. Agrega <code>fetch(self)</code> → <code>\"Rex fetches the ball\"</code>.</li><li><code>Cat(Animal)</code>: igual pero con sonido <code>\"miau\"</code>, y <strong>redefine</strong> <code>speak</code> → <code>\"Misi says miau... if she feels like it\"</code> (override total).</li></ul><p>Fijate qué heredan gratis: <code>cat.eat()</code> tiene que funcionar sin que Cat lo defina.</p>",
      starter: "class Animal:\n    pass\n\nclass Dog(Animal):\n    pass\n\nclass Cat(Animal):\n    pass\n",
      tests: "a = Animal(\"Generic\", \"...\")\nassert a.speak() == \"Generic says ...\"\nd = Dog(\"Rex\")\nassert d.speak() == \"Rex says guau\", f\"Dog hereda speak del padre: {d.speak()}\"\nassert d.eat() == \"Rex is eating\", \"eat se hereda gratis\"\nassert d.fetch() == \"Rex fetches the ball\"\nc = Cat(\"Misi\")\nassert c.speak() == \"Misi says miau... if she feels like it\", f\"Cat redefine speak: {c.speak()}\"\nassert c.eat() == \"Misi is eating\", \"Cat tambien hereda eat\"\nassert isinstance(d, Animal) and isinstance(c, Animal), \"Dog y Cat SON Animales\"",
      solution: "class Animal:\n    def __init__(self, name, sound):\n        self.name = name\n        self.sound = sound\n\n    def speak(self):\n        return f\"{self.name} says {self.sound}\"\n\n    def eat(self):\n        return f\"{self.name} is eating\"\n\nclass Dog(Animal):\n    def __init__(self, name):\n        super().__init__(name, \"guau\")\n\n    def fetch(self):\n        return f\"{self.name} fetches the ball\"\n\nclass Cat(Animal):\n    def __init__(self, name):\n        super().__init__(name, \"miau\")\n\n    def speak(self):\n        return f\"{self.name} says {self.sound}... if she feels like it\"",
      explanation: "<p>Tres grados de relación con el padre, los tres en este ejercicio:</p><p><strong>Heredar tal cual</strong>: <code>eat</code> no aparece en Dog ni Cat y ambos lo tienen — al no encontrarlo en la clase del objeto, Python sube por la jerarquía hasta encontrarlo. <strong>Extender</strong>: el <code>__init__</code> de Dog hace su parte (fijar \"guau\") y delega el resto a <code>super().__init__</code> — colaboración, no reemplazo. <strong>Redefinir</strong> (override): el <code>speak</code> de Cat eclipsa al del padre por completo; la búsqueda lo encuentra primero en Cat y ahí termina.</p><p>El test de <code>isinstance</code> sella el contrato semántico: un Dog ES UN Animal — donde el programa pida un Animal, un Dog sirve. Esa sustituibilidad es lo que vuelve útil la herencia (y cuando una subclase NO puede sustituir al padre honestamente, es señal de que la herencia estaba mal elegida — preferí composición).</p>",
      hints: ["super().__init__(name, \"guau\") dentro del __init__ de Dog: el padre hace el trabajo de guardar.", "Override = definir el método de nuevo en la subclase, mismo nombre. El de Cat puede seguir usando self.sound heredado.", "eat NO se escribe en Dog ni Cat: si los tests piden que funcione, es porque la herencia lo trae solo."]
    },
    {
      id: "adv-oop-5",
      title: "Polimorfismo: figuras que se miden solas",
      difficulty: 5,
      prompt: "<p>El final del tema junta todo:</p><ul><li><code>Circle</code>: <code>__init__(self, radius)</code>; método <code>area()</code> → π·r² (usá <code>math.pi</code>).</li><li><code>Rectangle</code>: <code>__init__(self, width, height)</code>; <code>area()</code> → ancho·alto.</li><li><code>Square(Rectangle)</code>: <code>__init__(self, side)</code> — un cuadrado ES un rectángulo de lados iguales: resolvelo con <code>super()</code>, sin redefinir <code>area</code>.</li><li><code>total_area(shapes)</code>: función que suma las áreas de una lista de figuras CUALESQUIERA — sin un solo <code>isinstance</code>, sin preguntar tipos: solo confiar en que cada una sabe medirse.</li></ul>",
      starter: "import math\n\nclass Circle:\n    pass\n\nclass Rectangle:\n    pass\n\nclass Square(Rectangle):\n    pass\n\ndef total_area(shapes):\n    pass\n",
      tests: "import math as _m\nc = Circle(1)\nassert abs(c.area() - _m.pi) < 1e-9, f\"Circle(1).area(): {c.area()}\"\nr = Rectangle(3, 4)\nassert r.area() == 12, f\"Rectangle(3,4).area(): {r.area()}\"\ns = Square(5)\nassert s.area() == 25, f\"Square(5).area(): {s.area()}\"\nassert isinstance(s, Rectangle), \"Square debe heredar de Rectangle\"\nassert abs(total_area([c, r, s]) - (_m.pi + 37)) < 1e-9, f\"total_area: {total_area([c, r, s])}\"\nassert total_area([]) == 0, \"lista vacia: 0\"",
      solution: "import math\n\nclass Circle:\n    def __init__(self, radius):\n        self.radius = radius\n\n    def area(self):\n        return math.pi * self.radius ** 2\n\nclass Rectangle:\n    def __init__(self, width, height):\n        self.width = width\n        self.height = height\n\n    def area(self):\n        return self.width * self.height\n\nclass Square(Rectangle):\n    def __init__(self, side):\n        super().__init__(side, side)\n\ndef total_area(shapes):\n    return sum(shape.area() for shape in shapes)",
      explanation: "<p><code>total_area</code> es el premio: una línea que funciona para círculos, rectángulos, cuadrados… y para el <code>Triangle</code> que alguien escriba el año que viene, sin tocarla. No pregunta \"¿qué sos?\" — pide \"medite\" y cada objeto responde con SU fórmula. Eso es polimorfismo, y fijate que Circle y Rectangle ni siquiera comparten padre: en Python alcanza con responder al mismo método (duck typing).</p><p>La alternativa sin polimorfismo sería una cadena de <code>isinstance</code> con la fórmula de cada figura adentro de total_area — que habría que editar con CADA figura nueva. Regla de olfato: un isinstance en cadena casi siempre es un método polimórfico pidiendo nacer.</p><p><code>Square</code> muestra la herencia más elegante posible: <code>super().__init__(side, side)</code> y nada más — toda la funcionalidad cae por gravedad. Y este patrón exacto es scikit-learn: todos los modelos responden a <code>.fit()</code> y <code>.predict()</code>, y por eso un mismo pipeline entrena cualquiera.</p>",
      hints: ["Circle y Rectangle son clases normales con __init__ y un método area().", "Square: def __init__(self, side): super().__init__(side, side) — y NO escribas area().", "total_area: sum(shape.area() for shape in shapes) — generator expression, sin preguntar tipos."]
    }
  ]
},

/* ---------------- Decoradores ---------------- */
{
  id: "decoradores",
  title: "Decoradores",
  intro: "Un decorador envuelve una función para agregarle comportamiento — logging, caché, validación — <strong>sin tocar su código</strong>. Es la consecuencia natural de que las funciones sean valores, y el patrón favorito de los frameworks (<code>@app.route</code>, <code>@pytest.fixture</code>…).",
  socratic: [
    {
      q: "Ya sabés que las funciones se pasan como argumentos. El paso que falta: una función que DEVUELVE una función fabricada adentro. ¿Qué pasa con las variables locales de la fábrica cuando la función fabricada las usa después?",
      a: "Sobreviven: la función fabricada \"recuerda\" el entorno donde nació — eso se llama <em>closure</em>. Si <code>make_multiplier(3)</code> define y devuelve <code>lambda x: x * factor</code>, ese factor=3 queda capturado adentro de la función devuelta para siempre, aunque make_multiplier ya haya terminado. Sin closures no hay decoradores: el wrapper necesita recordar a qué función envuelve."
    },
    {
      q: "<code>@shout</code> arriba de <code>def greet():</code> — ¿qué hace exactamente esa arroba? Sin magia: ¿a qué se traduce?",
      a: "Es azúcar puro para <code>greet = shout(greet)</code>: llamar al decorador pasándole la función recién definida, y re-asignar el nombre al resultado. Nada más. El decorador es una función que recibe una función y devuelve (normalmente) otra que la envuelve. Si entendés esa línea de traducción, entendés todos los decoradores que existen."
    },
    {
      q: "El wrapper típico se define como <code>def wrapper(*args, **kwargs):</code> y adentro llama <code>func(*args, **kwargs)</code>. ¿Por qué esa firma y no parámetros concretos?",
      a: "Porque el decorador debe servir para CUALQUIER función — de cero, dos o diez parámetros, con o sin keywords. <code>*args, **kwargs</code> es la firma universal: \"agarro lo que venga\", y al llamar con <code>*args, **kwargs</code> lo reenvío idéntico. El wrapper es un intermediario transparente: intercepta, hace su gracia, y pasa la llamada tal cual."
    },
    {
      q: "Después de decorar, <code>greet.__name__</code> dice \"wrapper\" en vez de \"greet\". ¿Por qué pasa y qué lo arregla?",
      a: "Porque el nombre <code>greet</code> ahora apunta literalmente al wrapper — la identidad de la función original quedó oculta adentro del closure. Lo arregla <code>@functools.wraps(func)</code> sobre el wrapper: copia nombre, docstring y metadata de la original a la envoltura. Parece cosmético hasta que un traceback o un debugger te muestra veinte funciones llamadas \"wrapper\". En decoradores serios, wraps no es opcional."
    }
  ],
  exercises: [
    {
      id: "adv-dec-1",
      title: "Precalentamiento: fábricas de funciones",
      difficulty: 1,
      prompt: "<p>Antes del decorador, sus dos ingredientes:</p><ol><li><code>apply_twice(func, value)</code> → aplica la función dos veces: <code>func(func(value))</code>. Con eso: <code>result = apply_twice(lambda x: x * 3, 5)</code> → <code>45</code>.</li><li><code>make_multiplier(factor)</code> → <strong>devuelve una función</strong> que multiplica por ese factor: <pre>triple = make_multiplier(3)\ntriple(10)   # 30</pre>La función interna se define ADENTRO (con def o lambda) y usa <code>factor</code> — que sobrevive gracias al closure.</li></ol>",
      starter: "def apply_twice(func, value):\n    pass\n\ndef make_multiplier(factor):\n    pass\n\n# result = apply_twice(lambda x: x * 3, 5)\n",
      tests: "assert apply_twice(lambda x: x * 3, 5) == 45, f\"apply_twice(x3, 5): {apply_twice(lambda x: x * 3, 5)}\"\nassert apply_twice(lambda s: s + \"!\", \"hey\") == \"hey!!\"\nassert result == 45, f\"result: {result}\"\ntriple = make_multiplier(3)\ndouble = make_multiplier(2)\nassert triple(10) == 30 and triple(7) == 21, f\"triple(10): {triple(10)}\"\nassert double(10) == 20, \"cada multiplicador recuerda SU factor\"\nassert callable(triple), \"make_multiplier debe devolver una FUNCION\"",
      solution: "def apply_twice(func, value):\n    return func(func(value))\n\ndef make_multiplier(factor):\n    def multiplier(x):\n        return x * factor\n    return multiplier\n\nresult = apply_twice(lambda x: x * 3, 5)",
      explanation: "<p><code>apply_twice</code> consume funciones; <code>make_multiplier</code> las <strong>produce</strong> — y esa producción es el salto mental. Seguilo despacio: al llamar <code>make_multiplier(3)</code>, se define una función nueva <code>multiplier</code> cuyo cuerpo menciona <code>factor</code>; se devuelve esa función SIN llamarla (sin paréntesis); y aunque make_multiplier ya terminó, <code>triple(10)</code> encuentra factor=3 vivo adentro del closure.</p><p>La prueba de que cada closure es independiente: <code>triple</code> y <code>double</code> conviven con factores distintos — dos llamadas a la fábrica, dos entornos capturados. Un decorador es exactamente esto con un ingrediente más: lo que la fábrica captura es <em>otra función</em>.</p>",
      hints: ["apply_twice es una línea: return func(func(value)).", "make_multiplier: def adentro de def. La interna usa factor; la externa la devuelve SIN paréntesis."]
    },
    {
      id: "adv-dec-2",
      title: "Tu primer decorador",
      difficulty: 2,
      prompt: "<p>Escribí el decorador <code>shout</code>: hace que cualquier función (sin argumentos, por ahora) devuelva su resultado en MAYÚSCULAS y con <code>\"!!!\"</code> al final.</p><pre>@shout\ndef greet():\n    return \"hola dojo\"\n\ngreet()   # \"HOLA DOJO!!!\"</pre><p>Estructura: <code>shout</code> recibe <code>func</code>, define adentro un <code>wrapper()</code> que llama a <code>func()</code> y transforma el resultado, y devuelve el wrapper. Aplicalo con <code>@shout</code> a la función <code>greet</code> del starter.</p>",
      starter: "def shout(func):\n    pass\n\n@shout\ndef greet():\n    return \"hola dojo\"\n\nprint(greet())\n",
      tests: "assert greet() == \"HOLA DOJO!!!\", f\"greet(): {greet()}\"\n@shout\ndef _farewell():\n    return \"chau\"\nassert _farewell() == \"CHAU!!!\", f\"el decorador debe servir para cualquier funcion: {_farewell()}\"\nassert callable(greet), \"greet decorada sigue siendo una funcion\"",
      solution: "def shout(func):\n    def wrapper():\n        result = func()\n        return result.upper() + \"!!!\"\n    return wrapper\n\n@shout\ndef greet():\n    return \"hola dojo\"",
      explanation: "<p>Traducí la arroba mentalmente: <code>@shout</code> sobre greet equivale a <code>greet = shout(greet)</code>. Entonces: shout recibió la greet original, fabricó un wrapper que la tiene capturada en su closure, y el nombre <code>greet</code> pasó a apuntar al wrapper. Cuando llamás <code>greet()</code>, ejecutás el wrapper → este llama a la original → transforma su resultado → te lo entrega. La original sigue existiendo, escondida e intacta — solo perdió su nombre público.</p><p>Eso explica el superpoder del patrón: agregaste comportamiento sin editar la función original. Mañana decorás veinte funciones con <code>@log_time</code> sin tocarles una línea, y pasado lo sacás borrando veinte arrobas.</p>",
      hints: ["Misma estructura que make_multiplier, pero la fábrica recibe una FUNCION: def wrapper(): result = func(); return result.upper() + \"!!!\" — y return wrapper.", "@shout va en la línea de arriba del def greet. Es exactamente greet = shout(greet)."]
    },
    {
      id: "adv-dec-3",
      title: "El decorador universal: *args y wraps",
      difficulty: 3,
      prompt: "<p>Escribí <code>count_calls</code>: un decorador que cuenta cuántas veces fue llamada la función, para CUALQUIER firma:</p><ul><li>El wrapper acepta <code>*args, **kwargs</code> y los reenvía a la función original, devolviendo su resultado intacto.</li><li>Lleva la cuenta en un atributo del propio wrapper: inicializá <code>wrapper.calls = 0</code> después de definirlo, e incrementalo en cada llamada (sí, las funciones aceptan atributos: son objetos).</li><li>Usá <code>@functools.wraps(func)</code> para que la decorada conserve su <code>__name__</code>.</li></ul><pre>@count_calls\ndef add(a, b):\n    return a + b\n\nadd(2, 3)   # 5\nadd(1, 1)   # 2\nadd.calls   # 2\nadd.__name__  # \"add\", gracias a wraps</pre>",
      starter: "import functools\n\ndef count_calls(func):\n    pass\n\n@count_calls\ndef add(a, b):\n    return a + b\n",
      tests: "assert add(2, 3) == 5, f\"add(2, 3): {add(2, 3)}\"\nassert add(10, b=20) == 30, \"debe funcionar tambien con keyword arguments\"\nassert add.calls == 2, f\"add.calls deberia ser 2, es {add.calls}\"\nadd(0, 0)\nassert add.calls == 3, f\"add.calls deberia ser 3, es {add.calls}\"\nassert add.__name__ == \"add\", f\"add.__name__ es '{add.__name__}' — te falta @functools.wraps(func) sobre el wrapper\"\n@count_calls\ndef _noop():\n    return None\n_noop()\nassert _noop.calls == 1 and add.calls == 3, \"cada funcion decorada lleva SU propia cuenta\"",
      solution: "import functools\n\ndef count_calls(func):\n    @functools.wraps(func)\n    def wrapper(*args, **kwargs):\n        wrapper.calls += 1\n        return func(*args, **kwargs)\n    wrapper.calls = 0\n    return wrapper\n\n@count_calls\ndef add(a, b):\n    return a + b",
      explanation: "<p>Este es el esqueleto canónico — el que vas a escribir cada vez que hagas un decorador serio: <code>wraps</code> arriba del wrapper, firma universal <code>*args, **kwargs</code>, reenvío idéntico, y <code>return wrapper</code>.</p><p>El truco del contador: <code>wrapper.calls</code> es un atributo pegado al objeto-función wrapper — estado que persiste entre llamadas y, clave, es <em>por función decorada</em>: cada vez que decorás algo, se fabrica un wrapper nuevo con su propio contador (los tests lo verificaron con _noop). Es la opción simple frente a variables globales o closures con <code>nonlocal</code>.</p><p>Y la prueba de <code>add.__name__ == \"add\"</code>: sin wraps habría dicho \"wrapper\". En producción esto importa de verdad — herramientas de debugging, profiling y serialización leen esa metadata.</p><p>Patrón completo en tu cabeza ahora: este decorador ES <code>@app.route</code> de Flask, <code>@lru_cache</code>, <code>@retry</code> — cambia qué hace el wrapper antes/después de llamar, nunca la estructura.</p>",
      hints: ["Esqueleto: def count_calls(func): / @functools.wraps(func) / def wrapper(*args, **kwargs): ... / wrapper.calls = 0 / return wrapper.", "El incremento va DENTRO del wrapper (corre en cada llamada); el = 0 va FUERA (corre una vez, al decorar).", "El wrapper debe devolver func(*args, **kwargs) — sin el return, todas las decoradas devuelven None."]
    },
    {
      id: "adv-dec-4",
      title: "Decoradores con argumentos",
      difficulty: 4,
      prompt: "<p>El jefe final de la sintaxis: <code>@repeat(3)</code> — un decorador <em>configurable</em>.</p><pre>@repeat(3)\ndef beep():\n    return \"beep\"\n\nbeep()   # [\"beep\", \"beep\", \"beep\"]</pre><p>Pensalo así: <code>repeat(3)</code> se LLAMA primero y debe devolver… un decorador común y corriente. O sea: tres niveles — <code>repeat(n)</code> afuera, el decorador en el medio, el wrapper adentro. El wrapper llama a la función <code>n</code> veces y devuelve la lista de resultados.</p>",
      starter: "import functools\n\ndef repeat(n):\n    pass\n\n@repeat(3)\ndef beep():\n    return \"beep\"\n",
      tests: "assert beep() == [\"beep\", \"beep\", \"beep\"], f\"beep(): {beep()}\"\n@repeat(2)\ndef _roll(x):\n    return x * 2\nassert _roll(5) == [10, 10], f\"con argumentos: {_roll(5)}\"\n@repeat(1)\ndef _once():\n    return \"solo\"\nassert _once() == [\"solo\"], \"repeat(1): lista de un elemento\"",
      solution: "import functools\n\ndef repeat(n):\n    def decorator(func):\n        @functools.wraps(func)\n        def wrapper(*args, **kwargs):\n            return [func(*args, **kwargs) for _ in range(n)]\n        return wrapper\n    return decorator\n\n@repeat(3)\ndef beep():\n    return \"beep\"",
      explanation: "<p>Desarmá <code>@repeat(3)</code> en dos tiempos: primero se evalúa <code>repeat(3)</code> — una llamada normal que devuelve <code>decorator</code> — y después la arroba aplica ESE resultado: <code>beep = decorator(beep)</code>. Por eso los tres niveles: la capa extra existe solo para capturar la configuración (<code>n</code>) en el closure, y las dos internas son el decorador clásico que ya dominás.</p><p>Truco de lectura para no perderte en código ajeno: <code>@nombre</code> pelado = decorador directo (dos niveles); <code>@nombre(...)</code> con paréntesis = fábrica de decoradores (tres niveles). La diferencia es ese par de paréntesis.</p><p>Y el wrapper reaprovecha una vieja amiga: la comprehension con <code>_</code> para \"n veces, descartando el índice\". Las herramientas se siguen componiendo.</p>",
      hints: ["Tres def anidados: repeat(n) → decorator(func) → wrapper(*args, **kwargs). Cada nivel devuelve el de adentro.", "El wrapper: return [func(*args, **kwargs) for _ in range(n)].", "Si te da TypeError al decorar, te falta un nivel: repeat debe DEVOLVER el decorador, no ser el decorador."]
    },
    {
      id: "adv-dec-5",
      title: "memoize: caché casero",
      difficulty: 5,
      prompt: "<p>Fibonacci recursivo es elegantísimo y catastróficamente lento: <code>fib(n)</code> recalcula los mismos valores millones de veces. Arreglalo SIN tocar fib — con un decorador:</p><ul><li><code>memoize(func)</code>: guarda en un dict <code>cache</code> (clave: <code>args</code>, la tupla de argumentos — ya es hashable) los resultados ya calculados. Si los args están en el caché, devuelve lo guardado sin llamar; si no, llama, guarda y devuelve.</li><li>Exponé el dict como <code>wrapper.cache</code> para inspeccionarlo.</li><li>Decorá la <code>fib</code> del starter y calculá <code>result = fib(30)</code> → <code>832040</code>. Sin memoize serían ~2.7 millones de llamadas; con memoize, 31.</li></ul>",
      starter: "import functools\n\ndef memoize(func):\n    pass\n\n@memoize\ndef fib(n):\n    if n < 2:\n        return n\n    return fib(n - 1) + fib(n - 2)\n\n# result = fib(30)\n",
      tests: "assert fib(10) == 55, f\"fib(10): {fib(10)}\"\nassert result == 832040, f\"fib(30): {result}\"\nassert hasattr(fib, \"cache\"), \"expone el dict como wrapper.cache\"\nassert fib.cache[(10,)] == 55, \"el cache deberia tener la entrada de fib(10)\"\nassert len(fib.cache) >= 31, f\"tras fib(30) el cache deberia tener al menos 31 entradas, tiene {len(fib.cache)}\"\nassert fib(50) == 12586269025, \"fib(50) deberia ser instantaneo con memoize — sin el, tardaria horas\"",
      solution: "import functools\n\ndef memoize(func):\n    cache = {}\n    @functools.wraps(func)\n    def wrapper(*args):\n        if args in cache:\n            return cache[args]\n        result = func(*args)\n        cache[args] = result\n        return result\n    wrapper.cache = cache\n    return wrapper\n\n@memoize\ndef fib(n):\n    if n < 2:\n        return n\n    return fib(n - 1) + fib(n - 2)\n\nresult = fib(30)",
      explanation: "<p>La magia silenciosa: como <code>@memoize</code> re-asignó el nombre <code>fib</code> al wrapper, las llamadas recursivas <em>de adentro de fib</em> — <code>fib(n-1)</code> — también pasan por el caché. La recursión entera quedó interceptada sin tocar una línea de la función. Por eso fib(50), que sin caché necesitaría ~40 mil millones de llamadas, salió al instante: cada subproblema se calcula UNA vez.</p><p>El caché vive en el closure (<code>cache = {}</code> en la fábrica): privado, persistente entre llamadas, uno por función decorada. La clave es <code>args</code> — posible solo porque las tuplas son hashables, ¿te acordás del porqué desde Básico?</p><p>Este trade-off — memoria a cambio de velocidad — se llama <em>memoización</em> y es tan central que Python lo trae de fábrica: <code>@functools.lru_cache</code> es tu memoize con esteroides (límite de tamaño, estadísticas). En ML lo vas a ver hasta en la sopa: cachear features, embeddings, resultados de preprocesamiento.</p>",
      hints: ["La fábrica crea cache = {} antes del wrapper; el wrapper pregunta if args in cache.", "Camino sin caché: llamar func(*args), guardar en cache[args], devolver. Camino con caché: return cache[args] directo.", "wrapper.cache = cache (fuera del wrapper) lo expone para los tests."]
    }
  ]
},

/* ---------------- Generadores ---------------- */
{
  id: "generadores",
  title: "Generadores e iteradores",
  intro: "Una función con <code>yield</code> no devuelve una lista: devuelve una <strong>promesa de valores</strong>, que se cumplen de a uno, a pedido. Lazy evaluation: procesar millones de elementos con la memoria de uno. Así se alimentan los modelos de ML con datasets que no entran en RAM.",
  socratic: [
    {
      q: "¿Qué pasa EXACTAMENTE cuando llamás a una función que contiene yield? Pista: ni una línea de su cuerpo se ejecuta.",
      a: "Devuelve un <em>objeto generador</em>, congelado en la línea cero. El cuerpo recién empieza a correr cuando alguien le pide el primer valor (un for, next(), list()). Corre hasta el primer yield, ENTREGA el valor y se pausa — con todas sus variables locales vivas — hasta el próximo pedido. Es una función que se puede pausar y reanudar: eso es todo el secreto."
    },
    {
      q: "<code>[x*x for x in range(10**9)]</code> vs <code>(x*x for x in range(10**9))</code> — corchetes vs paréntesis. ¿Cuál te funde la RAM y por qué?",
      a: "Los corchetes: la list comprehension construye los mil millones de valores YA, en memoria. Los paréntesis crean una <em>generator expression</em>: una receta que produce valores de a uno cuando se los piden — memoria constante, del tamaño de UN elemento. Si el consumidor es sum(), max(), un for — que procesan de a uno — la lista intermedia era puro desperdicio."
    },
    {
      q: "Un generador puede ser infinito — <code>while True: yield ...</code> — y no cuelga nada. ¿Cómo puede ser? ¿Y de quién es la responsabilidad de frenar?",
      a: "Porque el while True solo avanza UNA vuelta por pedido: sin pedidos, no hay ejecución. El generador propone, el consumidor dispone: un break, un islice, un zip con algo finito — el corte vive del lado de quien consume. Esta inversión es liberadora: definís \"todos los números primos\" como concepto, y cada uso decide cuántos necesita."
    },
    {
      q: "¿Qué pasa si recorrés dos veces el mismo generador? ¿Y qué te dice eso sobre cuándo NO usarlos?",
      a: "La segunda pasada no produce nada: los generadores se <strong>agotan</strong> — son un stream, no un almacén; no recuerdan ni rebobinan. Si necesitás múltiples pasadas, acceso por índice o len(), querés una lista. Regla práctica: generador para flujos que se consumen una vez (líneas de archivo, batches de entrenamiento); lista para datos que se consultan muchas veces."
    }
  ],
  exercises: [
    {
      id: "adv-gen-1",
      title: "Tu primer yield",
      difficulty: 1,
      prompt: "<p>Escribí el generador <code>countdown(n)</code>: produce n, n-1, …, 1 (sin el cero).</p><pre>list(countdown(5))   # [5, 4, 3, 2, 1]</pre><p>Después, para VER la pausa en acción: creá <code>gen = countdown(3)</code> y extraé los dos primeros valores a mano con <code>next(gen)</code> en <code>first</code> y <code>second</code>.</p>",
      starter: "def countdown(n):\n    # while con yield\n    pass\n\n# gen = countdown(3)\n# first = ?\n# second = ?\n",
      tests: "assert list(countdown(5)) == [5, 4, 3, 2, 1], f\"countdown(5): {list(countdown(5))}\"\nassert list(countdown(1)) == [1]\nassert list(countdown(0)) == [], \"countdown(0): nada que producir\"\nassert first == 3 and second == 2, f\"first={first}, second={second}\"\nimport types\nassert isinstance(countdown(3), types.GeneratorType), \"countdown debe ser un GENERADOR (usa yield, no return de lista)\"",
      solution: "def countdown(n):\n    while n > 0:\n        yield n\n        n -= 1\n\ngen = countdown(3)\nfirst = next(gen)\nsecond = next(gen)",
      explanation: "<p>Seguí la película de <code>next(gen)</code>: el cuerpo corre hasta <code>yield n</code> → entrega 3 → <strong>se congela ahí</strong>, con n=3 en suspenso. El segundo next descongela JUSTO después del yield: ejecuta <code>n -= 1</code>, vuelve al while, yield 2, congela. Cada next compra una vuelta de loop.</p><p>Compará con la versión lista (<code>result = []</code>, append, return): produce todo aunque el consumidor quisiera solo el primero. El generador es <em>bajo demanda</em>: trabajo proporcional a lo consumido.</p><p>Cuando el while termina (n llega a 0), el generador levanta <code>StopIteration</code> por dentro — la señal de \"no hay más\", que el for y list() atienden solos. Por eso <code>list(countdown(0))</code> dio lista vacía y no error.</p>",
      hints: ["while n > 0: / yield n / n -= 1 — yield en vez de append.", "next(gen) extrae UN valor y pausa. Dos nexts seguidos: 3 y 2."]
    },
    {
      id: "adv-gen-2",
      title: "Generator expressions",
      difficulty: 2,
      prompt: "<p>Con <code>nums = range(1, 1001)</code>:</p><ul><li><code>squares_sum</code>: la suma de los cuadrados de los pares, pasándole a <code>sum()</code> una <strong>generator expression</strong> — sin crear ninguna lista intermedia. (Cuando el genexp es el único argumento, los paréntesis de la función alcanzan: <code>sum(x ... for x ...)</code>.) → <code>167167000</code></li><li><code>first_big</code>: el primer cubo mayor a 100.000 — armá el genexp de cubos crecientes y pedile UNO con <code>next()</code> → <code>103823</code> (47³). Fijate la elegancia: definís infinitos candidatos, computás justo los necesarios.</li></ul>",
      starter: "nums = range(1, 1001)\n\n# squares_sum = sum( ... )\n\n# first_big = next( ... )\n",
      tests: "assert squares_sum == 167167000, f\"squares_sum: {squares_sum}\"\nassert first_big == 103823, f\"first_big: {first_big}\"",
      solution: "nums = range(1, 1001)\n\nsquares_sum = sum(x * x for x in nums if x % 2 == 0)\n\nfirst_big = next(x ** 3 for x in nums if x ** 3 > 100000)",
      explanation: "<p><code>sum(x * x for x in nums if x % 2 == 0)</code> — sintaxis de comprehension, semántica de stream: sum va pidiendo valores de a uno y acumulando; en ningún momento existen los 500 cuadrados juntos. Para este tamaño da igual; para mil millones es la diferencia entre correr y reventar. El reflejo profesional: si el resultado se consume de una pasada (sum, max, min, any, all, \" \".join), genexp; si se reusa, lista.</p><p>El segundo es más sutil: <code>next(genexp)</code> = \"dame el primero que cumpla\". La evaluación perezosa hace que solo se calculen los cubos del 1 al 47 — los otros 953 jamás existen. Es la versión expresión de tu viejo patrón \"asignar y break\".</p>",
      hints: ["Genexp dentro de sum: sum(x * x for x in nums if x % 2 == 0) — sin corchetes.", "next(EXPRESION for x in nums if CONDICION) te da el primer valor que el filtro deja pasar."]
    },
    {
      id: "adv-gen-3",
      title: "Generadores infinitos",
      difficulty: 3,
      prompt: "<p>Definí el infinito sin miedo:</p><ol><li><code>naturals()</code>: generador infinito 1, 2, 3, … (<code>while True</code> + yield, sin condición de corte — acá es legal).</li><li><code>take(gen, n)</code>: función NORMAL que extrae los primeros n valores de cualquier generador y los devuelve como lista (un for con contador y break, o enumerate).</li><li>Usalas juntas: <code>first_naturals = take(naturals(), 5)</code> → <code>[1, 2, 3, 4, 5]</code>, y <code>multiples_of_7 = take((x for x in naturals() if x % 7 == 0), 4)</code> → <code>[7, 14, 21, 28]</code>.</li></ol><p>Nunca hagas <code>list(naturals())</code> — eso SÍ cuelga: pedirle todo a lo infinito.</p>",
      starter: "def naturals():\n    pass\n\ndef take(gen, n):\n    pass\n\n# first_naturals = ?\n# multiples_of_7 = ?\n",
      tests: "assert first_naturals == [1, 2, 3, 4, 5], f\"first_naturals: {first_naturals}\"\nassert multiples_of_7 == [7, 14, 21, 28], f\"multiples_of_7: {multiples_of_7}\"\nassert take(naturals(), 0) == [], \"take con n=0: lista vacia\"\nassert take(naturals(), 1) == [1]\n_g = naturals()\ntake(_g, 3)\nassert next(_g) == 4, \"take consume el generador: el siguiente valor despues de tomar 3 es 4\"",
      solution: "def naturals():\n    n = 1\n    while True:\n        yield n\n        n += 1\n\ndef take(gen, n):\n    result = []\n    for value in gen:\n        if len(result) >= n:\n            break\n        result.append(value)\n    return result\n\nfirst_naturals = take(naturals(), 5)\nmultiples_of_7 = take((x for x in naturals() if x % 7 == 0), 4)",
      explanation: "<p>El reparto de poderes quedó a la vista: <code>naturals()</code> declara un concepto sin fin; <code>take</code> impone el límite desde afuera. El mismo naturals sirve para 5 valores hoy y 5 millones mañana — la política de corte no le pertenece.</p><p>El último test enseña algo crucial: take(\\_g, 3) <em>avanzó</em> el generador — el próximo next dio 4, no 1. Los generadores tienen estado y memoria de posición: compartir uno entre dos consumidores significa repartirse los valores (a veces es justo lo que querés; a veces es un bug desconcertante).</p><p>Y <code>multiples_of_7</code> compone tres ideas en una línea: generador infinito → genexp filtrante (también infinita, también perezosa) → take que materializa 4. Pipeline puro. La librería estándar trae esta familia completa en <code>itertools</code>: tu take es <code>itertools.islice</code>, y hay count, cycle, chain… — el aplauso es que ahora podrías escribirlas todas.</p>",
      hints: ["naturals: n = 1 / while True: / yield n / n += 1.", "take junta en una lista hasta tener n: el break corta el for ANTES de pedir el valor de más.", "Para multiples_of_7: pasale a take una genexp filtrante sobre naturals()."]
    },
    {
      id: "adv-gen-4",
      title: "Fibonacci perezoso",
      difficulty: 4,
      prompt: "<p>La secuencia de Fibonacci como stream infinito: <code>fibonacci()</code> genera 0, 1, 1, 2, 3, 5, 8, … para siempre.</p><ul><li>El estado son dos variables (<code>a, b = 0, 1</code>) y la transición es UNA asignación de tupla: <code>a, b = b, a + b</code> — ¿reconocés el truco del intercambio del primer día?</li><li><code>first_ten = take(fibonacci(), 10)</code> → <code>[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]</code> (reusá tu take, o copiala del ejercicio anterior).</li><li><code>big_fib</code>: el primer Fibonacci mayor a 1000, con <code>next</code> + genexp → <code>1597</code>.</li></ul><p>Compará mentalmente con la fib recursiva del tema decoradores: aquella RE-calculaba; esta fluye — cada valor cuesta una suma.</p>",
      starter: "def fibonacci():\n    pass\n\ndef take(gen, n):\n    result = []\n    for value in gen:\n        if len(result) >= n:\n            break\n        result.append(value)\n    return result\n\n# first_ten = ?\n# big_fib = ?\n",
      tests: "assert first_ten == [0, 1, 1, 2, 3, 5, 8, 13, 21, 34], f\"first_ten: {first_ten}\"\nassert big_fib == 1597, f\"big_fib: {big_fib}\"\nassert take(fibonacci(), 3) == [0, 1, 1], \"cada llamada a fibonacci() arranca de cero\"",
      solution: "def fibonacci():\n    a, b = 0, 1\n    while True:\n        yield a\n        a, b = b, a + b\n\ndef take(gen, n):\n    result = []\n    for value in gen:\n        if len(result) >= n:\n            break\n        result.append(value)\n    return result\n\nfirst_ten = take(fibonacci(), 10)\nbig_fib = next(x for x in fibonacci() if x > 1000)",
      explanation: "<p>Tres formas de Fibonacci conociste ya, y la comparación ES la lección: la <strong>recursiva</strong> (elegante, exponencialmente lenta sin caché), la <strong>memoizada</strong> (rápida, memoria proporcional a n), y esta <strong>generadora</strong>: tiempo lineal, memoria CONSTANTE — dos variables, produzca 10 valores o 10 millones. Para streams, imbatible.</p><p>La línea <code>a, b = b, a + b</code> es tu intercambio de variables del día uno, ascendido: el lado derecho se evalúa completo con los valores viejos, así que <code>a + b</code> usa el b de antes — sin variable temporal, sin bug de orden. Estado mínimo, transición atómica.</p><p>Plantilla mental para llevarte: <em>estado inicial → while True → yield estado → transición</em>. Con ella se escribe cualquier secuencia matemática, un lector de páginas de API, un data loader de batches infinitos para entrenar — el mismo molde exacto.</p>",
      hints: ["a, b = 0, 1 / while True: / yield a / a, b = b, a + b — cuatro líneas, infinitos Fibonacci.", "¿Te da [1, 1, 2...]? Estás yieldeando b o haciendo la transición antes del yield: el 0 va primero.", "big_fib: next(x for x in fibonacci() if x > 1000)."]
    },
    {
      id: "adv-gen-5",
      title: "Pipeline de generadores",
      difficulty: 5,
      prompt: "<p>El gran final: una cadena de procesamiento donde NADA se computa hasta el último momento. Sobre las líneas crudas del starter, armá tres etapas <strong>perezosas</strong> (generator expressions, ni una lista):</p><ol><li><code>stripped</code>: cada línea sin espacios en las puntas.</li><li><code>nonempty</code>: de las anteriores, solo las que no quedaron vacías.</li><li><code>errors</code>: de esas, solo las que empiezan con <code>\"ERROR\"</code> (método <code>.startswith</code>).</li></ol><p>Recién al final, materializá: <code>error_list = list(errors)</code> → <code>[\"ERROR disk full\", \"ERROR net down\"]</code>.</p><p>La gracia: cada línea cruda atraviesa las TRES etapas de un tirón y se descarta antes de que pase la siguiente — como una cinta transportadora, no como tres depósitos.</p>",
      starter: "raw_lines = [\n    \"  ERROR disk full  \",\n    \"   \",\n    \"INFO all good\",\n    \"\",\n    \"ERROR net down\",\n    \"  WARN slow  \",\n]\n\n# stripped = ( ... )\n# nonempty = ( ... )\n# errors = ( ... )\n# error_list = list(errors)\n",
      tests: "import types\nassert isinstance(stripped, types.GeneratorType), \"stripped debe ser GENERATOR expression (parentesis), no lista\"\nassert isinstance(nonempty, types.GeneratorType), \"nonempty debe ser generator expression\"\nassert isinstance(errors, types.GeneratorType), \"errors debe ser generator expression\"\nassert error_list == [\"ERROR disk full\", \"ERROR net down\"], f\"error_list: {error_list}\"",
      solution: "raw_lines = [\n    \"  ERROR disk full  \",\n    \"   \",\n    \"INFO all good\",\n    \"\",\n    \"ERROR net down\",\n    \"  WARN slow  \",\n]\n\nstripped = (line.strip() for line in raw_lines)\nnonempty = (line for line in stripped if line)\nerrors = (line for line in nonempty if line.startswith(\"ERROR\"))\n\nerror_list = list(errors)",
      explanation: "<p>Hasta la línea del <code>list()</code>, tu programa no procesó NADA: solo enchufó caños. Después, list() le pide un valor a errors → errors le pide a nonempty → nonempty a stripped → stripped toma UNA línea cruda, la limpia, sube por la cadena pasando (o no) los filtros… y recién entonces se pide la siguiente. Una línea en tránsito por vez: con un archivo de 100 GB, la memoria usada sería la de una línea.</p><p>Compará con la versión \"tres listas\": cada etapa materializaría su resultado completo antes de empezar la siguiente — tres copias del dataset en RAM, y si solo quisieras el primer error, habrías procesado todo igual.</p><p>Este patrón — <em>fuente → transformaciones perezosas → consumidor</em> — es la arquitectura literal de los data loaders de PyTorch y TensorFlow: leer muestras, decodificar, augmentar, armar batches… todo generadores encadenados que despiertan cuando el modelo pide el próximo batch. Lo acabás de escribir en miniatura.</p>",
      hints: ["Paréntesis, no corchetes: stripped = (line.strip() for line in raw_lines).", "Cada etapa itera sobre LA ANTERIOR: nonempty itera stripped, errors itera nonempty.", "if line (truthiness: el string vacío es falso) filtra las vacías; .startswith(\"ERROR\") las de error."]
    }
  ]
},

/* ---------------- Context managers ---------------- */
{
  id: "context",
  title: "Context managers",
  intro: "El <code>with</code> que venís usando con archivos es un protocolo abierto: cualquier objeto con <code>__enter__</code> y <code>__exit__</code> puede garantizar su propia limpieza. Adquirir y liberar, abrir y cerrar, empezar y terminar — con garantía anti-excepciones.",
  socratic: [
    {
      q: "Sin with, el patrón seguro es try/finally. ¿Qué tiene de malo, a escala, escribirlo a mano cada vez?",
      a: "Que la pareja \"adquirir/liberar\" queda partida en dos lugares (el open arriba, el close en el finally abajo) y CADA uso del recurso debe recordar el ritual completo. Multiplicalo por archivos, locks, conexiones, transacciones… El context manager empaqueta el ritual EN el recurso: quien lo usa escribe with y la limpieza viaja incluida. Es DRY aplicado al manejo de recursos."
    },
    {
      q: "¿Qué llama Python exactamente al entrar y salir de un bloque with? ¿Y qué hace el as?",
      a: "Al entrar: <code>obj.__enter__()</code>, y su valor de retorno es lo que captura el <code>as</code> (¡no necesariamente el objeto mismo!). Al salir — normal o por excepción — <code>obj.__exit__(exc_type, exc_value, traceback)</code>: tres argumentos que son None si todo fue bien, o describen la excepción si la hubo. El with es un try/finally con uniforme."
    },
    {
      q: "El __exit__ recibe la excepción y puede devolver True o False. ¿Qué significa cada cosa? ¿Qué peligro tiene devolver True alegremente?",
      a: "True = \"yo me hago cargo\": la excepción se SUPRIME y el programa sigue después del with como si nada. False/None = \"limpié lo mío, pero que siga viajando\". El peligro de True indiscriminado es el del except pelado: tragarse errores que no sabés manejar. Un context manager honesto suprime solo tipos específicos que entiende — como contextlib.suppress(FileNotFoundError)."
    },
    {
      q: "<code>@contextmanager</code> convierte un generador en context manager. ¿Cómo se reparte el cuerpo de ese generador alrededor del yield?",
      a: "Todo lo ANTES del yield es el __enter__ (preparación); el VALOR yieldeado es lo que recibe el as; todo lo DESPUÉS es el __exit__ (limpieza). Para que la limpieza corra incluso con excepciones, el yield va dentro de un try/finally. Un solo flujo lineal que se lee de arriba a abajo — para casos simples, mucho más liviano que la clase."
    }
  ],
  exercises: [
    {
      id: "adv-ctx-1",
      title: "El problema que with resuelve",
      difficulty: 1,
      prompt: "<p>Vas a sentir el dolor antes de conocer la cura. El starter trae <code>connect()</code> y <code>process(data)</code> — y process EXPLOTA con datos malos. Tu tarea, SIN with (todavía): garantizar que la conexión se cierre pase lo que pase.</p><ol><li>Llamá <code>conn = connect()</code>, y en un <code>try/finally</code>: procesá <code>\"good data\"</code> guardando en <code>result1</code>, y cerrá con <code>conn.close()</code> en el finally.</li><li>Repetí con <code>\"bad data\"</code>: el process va a tirar ValueError — atrapalo por afuera (envolvé en try/except), y verificá que la conexión <strong>igual</strong> se cerró.</li></ol><p>El registro <code>events</code> del starter anota cada apertura y cierre: los tests lo auditan.</p>",
      starter: "events = []\n\nclass Connection:\n    def close(self):\n        events.append(\"closed\")\n\ndef connect():\n    events.append(\"opened\")\n    return Connection()\n\ndef process(conn, data):\n    if data == \"bad data\":\n        raise ValueError(\"datos corruptos\")\n    return f\"processed: {data}\"\n\n# 1. caso feliz con try/finally\n# result1 = ?\n\n# 2. caso con explosion: try/except por afuera, finally adentro igual cierra\n",
      tests: "assert result1 == \"processed: good data\", f\"result1: {result1}\"\nassert events == [\"opened\", \"closed\", \"opened\", \"closed\"], f\"events: {events} — cada opened debe tener su closed, INCLUSO cuando process explota\"",
      solution: "events = []\n\nclass Connection:\n    def close(self):\n        events.append(\"closed\")\n\ndef connect():\n    events.append(\"opened\")\n    return Connection()\n\ndef process(conn, data):\n    if data == \"bad data\":\n        raise ValueError(\"datos corruptos\")\n    return f\"processed: {data}\"\n\nconn = connect()\ntry:\n    result1 = process(conn, \"good data\")\nfinally:\n    conn.close()\n\nconn = connect()\ntry:\n    try:\n        process(conn, \"bad data\")\n    finally:\n        conn.close()\nexcept ValueError:\n    pass",
      explanation: "<p>El audit trail cuenta la historia: dos opened, dos closed, intercalados — incluso en el segundo caso, donde process explotó a mitad de camino. El <code>finally</code> es la única garantía: corre con éxito, con excepción, con return.</p><p>Pero mirá el costo en el segundo caso: try adentro de try, seis líneas de andamiaje para tres de trabajo. Y CADA punto del programa que use conexiones repite el ritual. Eso — exactamente eso — es lo que el context manager empaqueta: en el próximo ejercicio convertís esta Connection en algo que se usa <code>with connect() as conn:</code> y el andamiaje desaparece de la vista del usuario para siempre.</p>",
      hints: ["Caso 1: conn = connect() / try: result1 = process(...) / finally: conn.close().", "Caso 2: el try/finally que cierra va ADENTRO; el try/except ValueError que atrapa va AFUERA envolviéndolo."]
    },
    {
      id: "adv-ctx-2",
      title: "__enter__ y __exit__",
      difficulty: 2,
      prompt: "<p>Ahora sí: convertí la conexión en context manager. Creá la clase <code>ManagedConnection</code>:</p><ul><li><code>__init__</code>: registra <code>\"init\"</code> en <code>events</code>.</li><li><code>__enter__</code>: registra <code>\"enter\"</code> y <strong>devuelve self</strong> (lo que captura el as).</li><li><code>__exit__(self, exc_type, exc_value, traceback)</code>: registra <code>\"exit\"</code>. No devuelvas True: las excepciones deben seguir su curso.</li><li>Método <code>send(self, msg)</code> → <code>\"sent: hola\"</code>.</li></ul><p>Usala: un with normal guardando <code>sent = conn.send(\"hola\")</code>, y después OTRO with donde adentro hagas <code>raise RuntimeError(\"boom\")</code> (atrapalo afuera con try/except) — para verificar que __exit__ corre igual.</p>",
      starter: "events = []\n\nclass ManagedConnection:\n    pass\n\n# with ManagedConnection() as conn:\n#     sent = conn.send(\"hola\")\n\n# segundo with que explota adentro, envuelto en try/except RuntimeError\n",
      tests: "assert sent == \"sent: hola\", f\"sent: {sent}\"\nassert events == [\"init\", \"enter\", \"exit\", \"init\", \"enter\", \"exit\"], f\"events: {events} — el segundo exit debe registrarse AUNQUE el bloque haya explotado\"",
      solution: "events = []\n\nclass ManagedConnection:\n    def __init__(self):\n        events.append(\"init\")\n\n    def __enter__(self):\n        events.append(\"enter\")\n        return self\n\n    def __exit__(self, exc_type, exc_value, traceback):\n        events.append(\"exit\")\n\n    def send(self, msg):\n        return f\"sent: {msg}\"\n\nwith ManagedConnection() as conn:\n    sent = conn.send(\"hola\")\n\ntry:\n    with ManagedConnection() as conn:\n        raise RuntimeError(\"boom\")\nexcept RuntimeError:\n    pass",
      explanation: "<p>Compará con el ejercicio anterior: el try/finally desapareció de la vista — vive ahora DENTRO del protocolo. El usuario escribe dos líneas limpias y la garantía viaja incluida. Esa mudanza del andamiaje, del punto de uso al recurso mismo, es todo el valor del patrón.</p><p>Detalles que importan: <code>__enter__</code> devuelve self porque el as lo necesita (olvidarlo es el bug clásico: <code>conn</code> queda None y el primer <code>conn.send</code> revienta con NoneType). Y <code>__exit__</code> sin return (= None = False) deja pasar las excepciones: el RuntimeError salió del with y lo atrapó tu except — el manager limpió, no censuró.</p><p>Los tres argumentos de __exit__ que ignoraste hoy son la puerta al próximo nivel: con ellos el manager puede INSPECCIONAR qué falló y decidir. Ejercicio 4.</p>",
      hints: ["Los tres dunders: __init__, __enter__ (return self !), __exit__(self, exc_type, exc_value, traceback).", "¿conn es None adentro del with? Te falta el return self en __enter__.", "El segundo with va dentro de try: ... except RuntimeError: pass — el raise adentro del bloque."]
    },
    {
      id: "adv-ctx-3",
      title: "@contextmanager: la vía rápida",
      difficulty: 3,
      prompt: "<p>La versión generador. Con <code>from contextlib import contextmanager</code>, escribí <code>xml_tag(name, output)</code>: un context manager que escribe la etiqueta de apertura en la lista <code>output</code>, cede el control, y escribe la de cierre — <strong>garantizado</strong> incluso si el bloque explota:</p><pre>output = []\nwith xml_tag(\"body\", output):\n    output.append(\"contenido\")\n# output == [\"&lt;body&gt;\", \"contenido\", \"&lt;/body&gt;\"]</pre><p>Estructura: append de apertura → <code>try: yield</code> → <code>finally:</code> append de cierre. Probá también el caso anidado del starter (un tag adentro de otro) y el caso con excepción.</p>",
      starter: "from contextlib import contextmanager\n\n@contextmanager\ndef xml_tag(name, output):\n    pass\n\noutput = []\nwith xml_tag(\"body\", output):\n    output.append(\"contenido\")\n\nnested = []\nwith xml_tag(\"html\", nested):\n    with xml_tag(\"body\", nested):\n        nested.append(\"hola\")\n\ncrashed = []\ntry:\n    with xml_tag(\"div\", crashed):\n        raise ValueError(\"boom\")\nexcept ValueError:\n    pass\n",
      tests: "assert output == [\"<body>\", \"contenido\", \"</body>\"], f\"output: {output}\"\nassert nested == [\"<html>\", \"<body>\", \"hola\", \"</body>\", \"</html>\"], f\"nested: {nested} — los tags se cierran de adentro hacia afuera\"\nassert crashed == [\"<div>\", \"</div>\"], f\"crashed: {crashed} — el tag debe cerrarse AUNQUE el bloque explote (te falta el try/finally alrededor del yield?)\"",
      solution: "from contextlib import contextmanager\n\n@contextmanager\ndef xml_tag(name, output):\n    output.append(f\"<{name}>\")\n    try:\n        yield\n    finally:\n        output.append(f\"</{name}>\")",
      explanation: "<p>Releé la función como un sándwich: pre-yield = entrada, yield = \"acá corre el bloque del usuario\", post-yield = salida. El decorador <code>@contextmanager</code> fabrica los __enter__/__exit__ a partir de ese único flujo lineal — cinco líneas contra la docena de la clase.</p><p>El test de <code>crashed</code> justifica el try/finally: sin él, la excepción del bloque mataría al generador antes del append de cierre — tag abierto para siempre. Con finally, la simetría es inquebrantable. (Si tu CM necesitara pasar algo al as, sería <code>yield ese_valor</code> — acá no hacía falta.)</p><p>Y el caso anidado muestra la composición gratis: dos withs anidados cierran en orden inverso al que abrieron (LIFO), como corresponde a XML — sin que escribieras una línea para lograrlo. ¿Cuándo clase y cuándo decorador? Decorador para rituales lineales como este; clase cuando el manager tiene estado complejo, métodos propios, o lógica fina sobre las excepciones (como el que viene).</p>",
      hints: ["Cuerpo: output.append(f\"<{name}>\") / try: yield / finally: output.append(f\"</{name}>\").", "Sin try/finally, el test de la excepción falla: el cierre tiene que correr SIEMPRE.", "El yield va pelado (sin valor): este with no usa as."]
    },
    {
      id: "adv-ctx-4",
      title: "__exit__ con criterio: suprimir selectivamente",
      difficulty: 4,
      prompt: "<p>Creá <code>Suppress</code>, tu versión de <code>contextlib.suppress</code>: un context manager que se traga SOLO los tipos de excepción que le indican, y deja pasar el resto.</p><pre>with Suppress(ValueError):\n    raise ValueError(\"ignorado\")   # no explota\nprint(\"sigo vivo\")\n\nwith Suppress(ValueError):\n    raise TypeError(\"este NO\")     # explota normalmente</pre><ul><li><code>__init__(self, *exc_types)</code>: guarda la tupla de tipos a suprimir.</li><li><code>__exit__</code>: devuelve <code>True</code> SOLO si hubo excepción y su tipo es de los tolerados — la herramienta es <code>issubclass(exc_type, self.exc_types)</code> (acepta tuplas). Ojo con el caso sin excepción: <code>exc_type</code> es <code>None</code> y issubclass con None explota.</li></ul>",
      starter: "class Suppress:\n    pass\n\nlog = []\n\nwith Suppress(ValueError):\n    log.append(\"antes\")\n    raise ValueError(\"ignorado\")\n    log.append(\"nunca llego\")\n\nlog.append(\"despues del with\")\n",
      tests: "assert log == [\"antes\", \"despues del with\"], f\"log: {log}\"\nwith Suppress(KeyError, IndexError):\n    raise KeyError(\"x\")\nwith Suppress(KeyError, IndexError):\n    raise IndexError(\"y\")\ntry:\n    with Suppress(ValueError):\n        raise TypeError(\"no tolerado\")\n    assert False, \"el TypeError debio propagarse: Suppress(ValueError) no debe tragarselo\"\nexcept TypeError:\n    pass\nwith Suppress(ValueError):\n    pass  # sin excepcion: no debe explotar el __exit__\n",
      solution: "class Suppress:\n    def __init__(self, *exc_types):\n        self.exc_types = exc_types\n\n    def __enter__(self):\n        return self\n\n    def __exit__(self, exc_type, exc_value, traceback):\n        if exc_type is None:\n            return False\n        return issubclass(exc_type, self.exc_types)",
      explanation: "<p>Acá el __exit__ dejó de ser un finally pasivo: <strong>inspecciona y decide</strong>. Su valor de retorno es un veredicto: True = \"excepción digerida, el programa sigue después del with\" (por eso log saltó de \"antes\" a \"despues del with\": el resto del bloque se abandonó, pero sin propagar nada); False = \"que siga viajando\" (el TypeError llegó intacto a tu except).</p><p>Los detalles profesionales: el guard del <code>exc_type is None</code> primero (salida limpia, nada que decidir — y sin él, issubclass(None, ...) revienta justo en el caso feliz). Y <code>issubclass</code> en vez de <code>==</code> o <code>in</code>: respeta la jerarquía de excepciones — Suppress(OSError) tolera también FileNotFoundError, que ES un OSError, igual que un except lo haría.</p><p>El <code>*exc_types</code> del init es tu viejo *args armando la tupla que issubclass consume directo: las piezas de tres niveles atrás, encajando solas. La versión oficial es <code>contextlib.suppress</code> — idéntica semántica; la tuya ya no le debe nada.</p>",
      hints: ["__init__(self, *exc_types): self.exc_types = exc_types — el asterisco junta los tipos en tupla.", "__exit__: primero if exc_type is None: return False. Después return issubclass(exc_type, self.exc_types).", "¿Explota el with vacío? issubclass no acepta None: te falta el guard del caso sin excepción."]
    },
    {
      id: "adv-ctx-5",
      title: "Transaction: todo o nada",
      difficulty: 5,
      prompt: "<p>El context manager con semántica de base de datos. <code>Transaction(data)</code> protege un dict: si el bloque termina bien, los cambios quedan (<em>commit</em>); si explota, el dict vuelve <strong>exactamente</strong> a su estado anterior (<em>rollback</em>) — y la excepción sigue su curso.</p><pre>account = {\"balance\": 100}\ntry:\n    with Transaction(account) as acc:\n        acc[\"balance\"] -= 30\n        raise RuntimeError(\"se corto la luz\")\nexcept RuntimeError:\n    pass\naccount[\"balance\"]   # 100 — como si nada hubiera pasado</pre><p>Diseño: en <code>__enter__</code>, guardá una COPIA del dict (<code>dict.copy()</code> — ¿por qué copia y no asignación? pensalo) y devolvé el dict original; en <code>__exit__</code>, si hubo excepción, restaurá: <code>clear()</code> + <code>update(copia)</code> sobre el original (no lo reemplaces: otras variables apuntan a ÉL).</p>",
      starter: "class Transaction:\n    pass\n\naccount = {\"balance\": 100, \"owner\": \"ana\"}\n\n# caso feliz: los cambios persisten\nwith Transaction(account) as acc:\n    acc[\"balance\"] += 50\n\nhappy_balance = account[\"balance\"]   # 150\n\n# caso con explosion: rollback total\ntry:\n    with Transaction(account) as acc:\n        acc[\"balance\"] -= 99999\n        acc[\"owner\"] = \"hacker\"\n        raise RuntimeError(\"corte de luz\")\nexcept RuntimeError:\n    pass\n",
      tests: "assert happy_balance == 150, f\"happy_balance: {happy_balance} — sin excepcion, los cambios persisten\"\nassert account[\"balance\"] == 150, f\"balance final: {account['balance']} — el rollback debio restaurar el estado pre-transaccion (150)\"\nassert account[\"owner\"] == \"ana\", f\"owner: {account['owner']} — el rollback debe restaurar TODAS las claves\"\nd = {\"x\": 1}\nwith Transaction(d) as t:\n    t[\"y\"] = 2\nassert d == {\"x\": 1, \"y\": 2}, \"commit: claves nuevas persisten\"\ntry:\n    with Transaction(d) as t:\n        del t[\"x\"]\n        t[\"z\"] = 3\n        raise ValueError(\"abort\")\nexcept ValueError:\n    pass\nassert d == {\"x\": 1, \"y\": 2}, f\"rollback debe deshacer deletes y agregados: {d}\"",
      solution: "class Transaction:\n    def __init__(self, data):\n        self.data = data\n\n    def __enter__(self):\n        self.backup = self.data.copy()\n        return self.data\n\n    def __exit__(self, exc_type, exc_value, traceback):\n        if exc_type is not None:\n            self.data.clear()\n            self.data.update(self.backup)\n        return False",
      explanation: "<p>Las dos preguntas del enunciado eran el corazón del ejercicio:</p><p><strong>¿Por qué .copy() y no <code>backup = data</code>?</strong> Tu viejo enemigo el aliasing: la asignación pegaría una segunda etiqueta al MISMO dict — al \"restaurar\" desde él, restaurarías el dict corrupto desde sí mismo. La copia congela el estado de verdad. (Para dicts con listas adentro haría falta <code>deepcopy</code> — la copia superficial comparte los objetos internos.)</p><p><strong>¿Por qué clear() + update() y no <code>self.data = self.backup</code>?</strong> Aliasing otra vez, del lado bueno: <code>account</code> (afuera) y <code>self.data</code> apuntan al mismo objeto — mutarlo IN PLACE hace que todos los que lo conocen vean la restauración. Reasignar solo movería la etiqueta interna del Transaction; account quedaría corrupto. Mutación in place = el cambio es de todos; reasignación = el cambio es solo tuyo.</p><p>Y el <code>return False</code> final: rollback ≠ censura — el estado se restaura pero el RuntimeError sigue viajando, porque quien llamó merece saber que la operación NO ocurrió. Semántica exacta de una transacción de base de datos: atomicidad (todo o nada) sin silencio. El nivel cierra acá: aliasing del día 2, excepciones de Intermedio y el protocolo with, trabajando juntos en 12 líneas.</p>",
      hints: ["__enter__: self.backup = self.data.copy() y return self.data.", "__exit__: if exc_type is not None: self.data.clear() / self.data.update(self.backup). Y return False para no tragarte la excepción.", "¿El rollback 'no funciona'? Si hiciste backup = self.data sin .copy(), tu respaldo es el mismo dict que estás corrompiendo."]
    }
  ]
},

/* ---------------- Type hints ---------------- */
{
  id: "typehints",
  title: "Type hints",
  intro: "Python sigue siendo dinámico, pero desde hace años habla un segundo idioma: las anotaciones de tipo. <code>def f(x: int) -&gt; str</code> documenta, alimenta el autocompletado, y deja que herramientas como mypy cacen bugs SIN ejecutar. En código profesional moderno, son la norma.",
  socratic: [
    {
      q: "Si Python IGNORA los type hints en ejecución (podés pasarle un str a un parámetro anotado int y corre igual), ¿para qué sirven?",
      a: "Para los otros dos lectores de tu código: los humanos y las herramientas. El humano lee la firma y sabe el contrato sin bucear en el cuerpo. Las herramientas (mypy, pyright, tu editor) verifican TODO el programa en frío: cada llamada, cada return, cada atributo — y te subrayan el bug antes de correr nada. Es documentación que no puede mentir, porque un verificador la chequea contra el código real."
    },
    {
      q: "¿Qué significa exactamente <code>def parse(s: str) -&gt; int | None:</code>? ¿Qué obligación le crea a quien la llama?",
      a: "Que parse devuelve un int O None — el None como posibilidad EXPLÍCITA en el contrato. La obligación: quien llama debe manejar el caso None antes de usar el resultado como int, y un type checker se lo exige (\"possibly None\"). Esto convierte el bug más común de Python — el None inesperado que explota lejos — en un error señalado en tiempo de desarrollo. La sintaxis vieja que verás en código existente: Optional[int]."
    },
    {
      q: "Las @dataclass generan __init__, __repr__ y __eq__ a partir de los campos anotados. ¿Qué relación profunda hay entre dataclasses y type hints?",
      a: "La dataclass LEE las anotaciones para saber qué campos existen — sin hints no hay dataclass: son la única declaración. Es el ejemplo perfecto de anotaciones que dejan de ser comentarios y se vuelven motor: la clase entera se genera desde los tipos. El patrón se repite por todo el ecosistema: pydantic valida APIs, FastAPI genera documentación, todo desde las firmas tipadas."
    },
    {
      q: "Para una función como <code>first(items)</code> que devuelve el primer elemento: anotarla <code>list -&gt; object</code> pierde información. ¿Qué problema resuelve un TypeVar?",
      a: "El de la CONEXIÓN entre entrada y salida: con <code>T = TypeVar(\"T\")</code> y <code>first(items: list[T]) -&gt; T</code>, decís \"devuelvo el MISMO tipo que contiene la lista, sea cual sea\". Así first(nombres) devuelve str para el checker, y first(nums) devuelve int — sin escribir dos funciones. Eso es programación genérica: tipos como variables. Toda la librería estándar está anotada así."
    }
  ],
  exercises: [
    {
      id: "adv-hint-1",
      title: "Anotando tu primera firma",
      difficulty: 1,
      prompt: "<p>Tomá esta función y anotala completa: <code>def repeat_word(word, times):</code> que devuelve la palabra repetida con espacios — <code>repeat_word(\"go\", 3)</code> → <code>\"go go go\"</code>.</p><ul><li><code>word</code> es str, <code>times</code> es int, y el retorno es str: la sintaxis es <code>def f(a: tipo, b: tipo) -&gt; tipo:</code></li><li>Implementala (pista de una línea: ya conocés <code>join</code> y la multiplicación de listas <code>[word] * times</code>).</li><li>Después espiá <code>repeat_word.__annotations__</code> con un print — las anotaciones quedan guardadas, vivas, en la función.</li></ul>",
      starter: "def repeat_word(word, times):\n    pass\n\nprint(repeat_word(\"go\", 3))\nprint(repeat_word.__annotations__)\n",
      tests: "assert repeat_word(\"go\", 3) == \"go go go\", f\"repeat_word('go', 3): {repeat_word('go', 3)!r}\"\nassert repeat_word(\"na\", 1) == \"na\"\n_ann = repeat_word.__annotations__\nassert _ann.get(\"word\") is str, f\"word debe anotarse como str: {_ann}\"\nassert _ann.get(\"times\") is int, f\"times debe anotarse como int: {_ann}\"\nassert _ann.get(\"return\") is str, f\"el tipo de retorno (-> str) falta o es incorrecto: {_ann}\"",
      solution: "def repeat_word(word: str, times: int) -> str:\n    return \" \".join([word] * times)",
      explanation: "<p>La firma ahora ES el contrato: \"dame un str y un int, te devuelvo un str\" — legible para humanos, verificable para máquinas. Y como mostró el print, las anotaciones no se evaporan: viven en <code>__annotations__</code> (el retorno bajo la clave \"return\"), donde las herramientas las encuentran.</p><p>Vale repetir la regla del juego: Python NO valida esto al correr — <code>repeat_word(5, \"x\")</code> ejecutaría (y fallaría a su manera). La validación es estática, de las herramientas. Ese diseño deliberado (\"gradual typing\") permite anotar un proyecto de a poco, archivo por archivo, sin romper nada.</p><p>(<code>[word] * times</code> + join: dos viejos conocidos resolviendo el cuerpo. La multiplicación de listas repite elementos; join pega con espacios.)</p>",
      hints: ["def repeat_word(word: str, times: int) -> str: — dos puntos para parámetros, flecha para el retorno.", "El cuerpo en una línea: \" \".join([word] * times)."]
    },
    {
      id: "adv-hint-2",
      title: "Tipos genéricos: list, dict y sus contenidos",
      difficulty: 2,
      prompt: "<p>Las colecciones se anotan CON su contenido: <code>list[int]</code>, <code>dict[str, float]</code>. Implementá y anotá por completo:</p><ul><li><code>average(values: list[float]) -&gt; float</code> — el promedio (lista vacía → 0.0).</li><li><code>grade_averages(grades: dict[str, list[int]]) -&gt; dict[str, float]</code> — recibe <code>{alumno: [notas]}</code> y devuelve <code>{alumno: promedio}</code>. Una dict comprehension que reuse average.</li></ul><p>Leé en voz alta el tipo del segundo parámetro: \"dict de str a lista de ints\". Si podés pronunciarlo, podés escribirlo.</p>",
      starter: "def average(values):\n    pass\n\ndef grade_averages(grades):\n    pass\n\n# proba:\n# print(grade_averages({\"ana\": [8, 9, 10], \"beto\": [6, 7]}))\n",
      tests: "assert average([8.0, 9.0, 10.0]) == 9.0, f\"average: {average([8.0, 9.0, 10.0])}\"\nassert average([]) == 0.0, \"lista vacia: 0.0\"\n_r = grade_averages({\"ana\": [8, 9, 10], \"beto\": [6, 7]})\nassert _r == {\"ana\": 9.0, \"beto\": 6.5}, f\"grade_averages: {_r}\"\n_a1 = average.__annotations__\nassert str(_a1.get(\"values\")) in (\"list[float]\", \"typing.List[float]\"), f\"values: anotalo list[float] — {_a1}\"\nassert _a1.get(\"return\") is float, f\"average debe retornar float: {_a1}\"\n_a2 = grade_averages.__annotations__\nassert \"dict[str, list[int]]\" in str(_a2.get(\"grades\")).replace(\"typing.\", \"\").replace(\"List\", \"list\").replace(\"Dict\", \"dict\"), f\"grades: dict[str, list[int]] — {_a2}\"",
      solution: "def average(values: list[float]) -> float:\n    if not values:\n        return 0.0\n    return sum(values) / len(values)\n\ndef grade_averages(grades: dict[str, list[int]]) -> dict[str, float]:\n    return {name: average(scores) for name, scores in grades.items()}",
      explanation: "<p><code>dict[str, list[int]]</code> se lee de afuera hacia adentro, como las estructuras anidadas que ya navegás: dict cuyas claves son str y cuyos valores son listas de int. Los tipos anidan exactamente igual que los datos — porque DESCRIBEN los datos.</p><p>Lo que un type checker haría con esto: si adentro de grade_averages escribieras <code>scores.upper()</code>, lo marca (las list[int] no tienen upper); si llamaras <code>grade_averages([1, 2])</code>, lo marca. Cada anotación es una red más bajo el trapecio.</p><p>Detalle histórico que vas a cruzar: antes de Python 3.9 se escribía <code>List[float]</code> y <code>Dict[str, ...]</code> importados de typing — montañas de código viejo lo tienen. Mismo significado; hoy se usan las minúsculas nativas.</p>",
      hints: ["average(values: list[float]) -> float — y el guard de lista vacía primero.", "El tipo compuesto se arma anidando: dict[str, list[int]]. El retorno: dict[str, float].", "grade_averages: {name: average(scores) for name, scores in grades.items()}."]
    },
    {
      id: "adv-hint-3",
      title: "El contrato del None: Optional",
      difficulty: 3,
      prompt: "<p>Implementá <code>find_user(users: list[dict], name: str) -&gt; dict | None</code>: busca en una lista de dicts el primero cuyo campo <code>\"name\"</code> coincida (sin distinguir mayúsculas); si nadie coincide, devuelve None — y la anotación <code>dict | None</code> lo declara abiertamente.</p><p>Después usala con disciplina de type checker: buscá a <code>\"ADA\"</code> y armá <code>greeting</code> — pero como el resultado PUEDE ser None, chequealo antes de acceder: si existe, <code>f\"hola {user['name']}\"</code>; si no, <code>\"usuario no encontrado\"</code>. Repetí con <code>\"zoe\"</code> en <code>greeting2</code>.</p>",
      starter: "users = [\n    {\"name\": \"ada\", \"role\": \"admin\"},\n    {\"name\": \"beto\", \"role\": \"dev\"},\n]\n\ndef find_user(users, name):\n    pass\n\n# greeting = ?   (buscando \"ADA\")\n# greeting2 = ?  (buscando \"zoe\")\n",
      tests: "assert find_user(users, \"ada\") == {\"name\": \"ada\", \"role\": \"admin\"}\nassert find_user(users, \"BETO\") == {\"name\": \"beto\", \"role\": \"dev\"}, \"la busqueda no debe distinguir mayusculas\"\nassert find_user(users, \"zoe\") is None, \"sin coincidencia: None, no excepcion\"\nassert greeting == \"hola ada\", f\"greeting: {greeting}\"\nassert greeting2 == \"usuario no encontrado\", f\"greeting2: {greeting2}\"\n_ann = str(find_user.__annotations__.get(\"return\", \"\"))\nassert \"None\" in _ann, f\"el retorno debe anotarse dict | None (u Optional[dict]): {find_user.__annotations__}\"",
      solution: "users = [\n    {\"name\": \"ada\", \"role\": \"admin\"},\n    {\"name\": \"beto\", \"role\": \"dev\"},\n]\n\ndef find_user(users: list[dict], name: str) -> dict | None:\n    for user in users:\n        if user[\"name\"].lower() == name.lower():\n            return user\n    return None\n\nuser = find_user(users, \"ADA\")\ngreeting = f\"hola {user['name']}\" if user is not None else \"usuario no encontrado\"\n\nuser2 = find_user(users, \"zoe\")\ngreeting2 = f\"hola {user2['name']}\" if user2 is not None else \"usuario no encontrado\"",
      explanation: "<p>El patrón \"buscar\" canónico: loop + return temprano al encontrar + <code>return None</code> explícito al final (técnicamente redundante — la función caería en None igual — pero declararlo dice \"esto es a propósito, no un olvido\").</p><p>La segunda mitad es la disciplina que el tipo impone: <code>dict | None</code> grita \"¡puedo no encontrar!\", y el código que la llama DEBE bifurcar antes de tocar el resultado. Ese chequeo (<code>if user is not None</code>) se llama <em>narrowing</em>: dentro de la rama, el tipo se estrecha de \"dict | None\" a \"dict\" y el acceso es seguro. Los type checkers hacen ese razonamiento línea por línea y rechazan el acceso sin chequeo.</p><p>Comparalo con la alternativa sin contrato: find_user que a veces da None sin anunciarlo, el None viaja, y tres funciones después: <code>TypeError: 'NoneType' object is not subscriptable</code> a las 3 AM. La anotación mueve ese error de producción a tu editor, hoy.</p>",
      hints: ["La anotación clave: -> dict | None. La búsqueda: comparar user[\"name\"].lower() == name.lower().", "Para los greetings, el ternario con guard: f\"hola {user['name']}\" if user is not None else \"usuario no encontrado\".", "Guardá el resultado de find_user en una variable ANTES del ternario: lo necesitás dos veces (chequear y usar)."]
    },
    {
      id: "adv-hint-4",
      title: "dataclasses: clases a partir de tipos",
      difficulty: 4,
      prompt: "<p>Reescribí la clase Book del tema OOP, versión 2026. Con <code>from dataclasses import dataclass</code>:</p><pre>@dataclass\nclass Book:\n    title: str\n    author: str\n    year: int\n    available: bool = True</pre><p>Eso es TODO: __init__, __repr__ y __eq__ se generan solos desde los campos anotados. Agregale un método normal <code>age(self, current_year: int) -&gt; int</code> que devuelva los años desde su publicación. Después creá <code>b1 = Book(\"Dune\", \"Frank Herbert\", 1965)</code>, su gemelo <code>b2</code> con los mismos datos, y verificá con un print que <code>b1 == b2</code> — ¿daría True en una clase normal sin __eq__? (Probalo mentalmente: ¿qué compararía?)</p>",
      starter: "from dataclasses import dataclass\n\n# @dataclass\n# class Book: ...\n\n# b1 = ?\n# b2 = ?\n",
      tests: "b = Book(\"Dune\", \"Frank Herbert\", 1965)\nassert b.title == \"Dune\" and b.year == 1965, \"el __init__ generado debe asignar los campos\"\nassert b.available is True, \"available tiene default True\"\nb_used = Book(\"Dune\", \"Frank Herbert\", 1965, False)\nassert b_used.available is False\nassert b1 == b2, \"dos Books con los mismos datos deben ser == (eso regala la dataclass)\"\nassert b1 is not b2, \"iguales en contenido, pero objetos DISTINTOS\"\nassert b.age(2026) == 61, f\"age: {b.age(2026)}\"\nassert \"Dune\" in repr(b), f\"el __repr__ generado muestra los campos: {repr(b)}\"\nimport dataclasses as _dc\nassert _dc.is_dataclass(Book), \"Book debe ser una @dataclass\"",
      solution: "from dataclasses import dataclass\n\n@dataclass\nclass Book:\n    title: str\n    author: str\n    year: int\n    available: bool = True\n\n    def age(self, current_year: int) -> int:\n        return current_year - self.year\n\nb1 = Book(\"Dune\", \"Frank Herbert\", 1965)\nb2 = Book(\"Dune\", \"Frank Herbert\", 1965)",
      explanation: "<p>Compará con tu Book de OOP: el __init__ de asignaciones mecánicas (<code>self.title = title</code>…), el __repr__ artesanal — todo ese texto repetitivo (\"boilerplate\") lo generó el decorador a partir de cuatro líneas de campos anotados. Y de regalo, <code>__eq__</code>: comparación campo por campo. En una clase normal, <code>b1 == b2</code> daría <strong>False</strong> — sin __eq__, Python compara identidad (¿mismo objeto?), tu viejo <code>is</code> disfrazado.</p><p>Notá la inversión filosófica: las anotaciones, que en funciones eran documentación pasiva, acá son LA definición — la dataclass no existe sin ellas. Los métodos normales (age) conviven sin drama: es una clase común con el boilerplate automatizado.</p><p>Cuándo usarlas: cada vez que una clase es principalmente DATOS con algo de comportamiento — configs, registros, resultados, DTOs. Es la evolución natural de tus tuplas-registro de Básico: (title, author, year) → Book con nombres, tipos, defaults y métodos. El ecosistema entero va por esta vía (pydantic, attrs); reconocerla es leer Python moderno.</p>",
      hints: ["@dataclass arriba, y el cuerpo son solo campos anotados: title: str (etc.), available: bool = True al final (defaults al final, como en funciones).", "age es un método normal dentro de la clase, con self: return current_year - self.year.", "b1 y b2: dos llamadas Book(...) con los mismos argumentos. El == lo regala el decorador."]
    },
    {
      id: "adv-hint-5",
      title: "Genéricos: TypeVar y Callable",
      difficulty: 5,
      prompt: "<p>El nivel final del sistema de tipos. Con <code>from typing import TypeVar, Callable</code>:</p><ol><li>Declará <code>T = TypeVar(\"T\")</code> y escribí <code>first(items: list[T]) -&gt; T</code>: devuelve el primer elemento; lista vacía → <code>raise ValueError(\"lista vacia\")</code>. El TypeVar promete: \"retorno EL tipo del contenido\".</li><li><code>apply_n(func: Callable[[T], T], value: T, times: int) -&gt; T</code>: aplica func al valor, times veces encadenadas — <code>apply_n(double, 1, 3)</code> es double(double(double(1))). <code>Callable[[T], T]</code> describe \"función que toma un T y devuelve un T\" — tu apply_twice de decoradores, ahora con contrato.</li></ol>",
      starter: "from typing import TypeVar, Callable\n\n# T = ?\n\ndef first(items):\n    pass\n\ndef apply_n(func, value, times):\n    pass\n\n# proba:\n# print(first([10, 20, 30]))\n# print(apply_n(lambda x: x * 2, 1, 10))\n",
      tests: "assert first([10, 20, 30]) == 10\nassert first([\"a\", \"b\"]) == \"a\", \"first funciona con cualquier tipo: eso ES el generico\"\ntry:\n    first([])\n    assert False, \"lista vacia: ValueError\"\nexcept ValueError:\n    pass\nassert apply_n(lambda x: x * 2, 1, 10) == 1024, f\"apply_n duplicando 10 veces: {apply_n(lambda x: x * 2, 1, 10)}\"\nassert apply_n(lambda s: s + \"!\", \"ey\", 3) == \"ey!!!\", f\"apply_n con strings: {apply_n(lambda s: s + '!', 'ey', 3)}\"\nassert apply_n(lambda x: x, 99, 0) == 99, \"times=0: el valor intacto\"\nfrom typing import TypeVar as _TV\nassert type(T) is type(_TV(\"X\")), \"T debe ser un TypeVar\"\nassert \"T\" in str(first.__annotations__), f\"first debe anotarse con el TypeVar: {first.__annotations__}\"",
      solution: "from typing import TypeVar, Callable\n\nT = TypeVar(\"T\")\n\ndef first(items: list[T]) -> T:\n    if not items:\n        raise ValueError(\"lista vacia\")\n    return items[0]\n\ndef apply_n(func: Callable[[T], T], value: T, times: int) -> T:\n    for _ in range(times):\n        value = func(value)\n    return value",
      explanation: "<p><code>T</code> es una variable, pero de tipos: en cada LLAMADA toma un valor distinto — first(lista_de_ints) liga T=int y el checker sabe que sale un int; first(strings) liga T=str. Una firma, infinitos contratos precisos. Sin el TypeVar, la única anotación honesta sería el inútil \"object\": sabrías que algo sale, no qué.</p><p><code>Callable[[T], T]</code> en apply_n agrega la restricción fina: la función debe devolver LO MISMO que recibe — si no, no podrías encadenarla. <code>Callable[[int, str], bool]</code> describiría otra firma; los corchetes internos listan los parámetros. Con esto, tus funciones de orden superior de Intermedio (map, filter, los decoradores) tienen por fin vocabulario para sus contratos.</p><p>Y el cierre del cierre: la implementación de apply_n es un humilde loop con reasignación — todo este nivel fue eso: ideas simples de Básico (loops, funciones, dicts) ganando capas de expresividad (closures, protocolos, tipos) sin cambiar de esencia. Estás listo para el proyecto.</p>",
      hints: ["T = TypeVar(\"T\") — el string y el nombre coinciden por convención.", "first: anotá list[T] -> T; el cuerpo es un guard + return items[0].", "apply_n: for _ in range(times): value = func(value) — y devolvé value. La anotación de func: Callable[[T], T]."]
    }
  ]
},

/* ---------------- PROYECTO AVANZADO ---------------- */
{
  id: "proyecto-avanzado",
  title: "Proyecto: Sistema de biblioteca",
  isProject: true,
  intro: "El examen de arquitectura: dataclasses, excepciones propias, generadores, un context manager y type hints — colaborando en un sistema de préstamos de libros que se sostiene solo.",
  socratic: [
    {
      q: "El proyecto pide una excepción propia: <code>class BookNotAvailable(Exception)</code>. ¿Qué gana tu sistema con un tipo de error propio en vez de un ValueError genérico?",
      a: "Vocabulario de dominio en el manejo de errores: quien usa la biblioteca puede escribir <code>except BookNotAvailable:</code> y manejar EXACTAMENTE ese caso de negocio, sin riesgo de atrapar por accidente un ValueError ajeno (un bug de parseo, por ejemplo). Las excepciones propias son parte de la API pública: nombran lo que puede salir mal en TU dominio. Definirla cuesta dos líneas — class X(Exception): pass — y paga para siempre."
    },
    {
      q: "search() debe ser un generador, no devolver una lista. En una biblioteca real de un millón de libros, ¿qué cambia para el que busca \"el primero que coincida\"?",
      a: "Todo: el generador examina libros solo mientras alguien pide resultados — next(search(...)) toca, en promedio, una fracción del catálogo y corta. La versión lista recorrería el millón completo, armaría la lista entera… para usar el primer elemento. La pereza convierte \"buscar\" de costo fijo (todo el catálogo) a costo proporcional al interés del consumidor."
    },
    {
      q: "LoanSession es un context manager que auto-devuelve los libros al salir. ¿Qué invariante del sistema garantiza, y contra qué tipo de bug protege?",
      a: "El invariante \"todo libro prestado en una sesión vuelve al estante cuando la sesión termina\" — INCLUSO si el código del usuario explota a mitad de sesión. Protege contra el leak clásico: el préstamo huérfano, un libro marcado no-disponible para siempre porque la excepción saltó antes del return_book. Es tu Transaction del tema anterior con ropa de dominio: adquirir/liberar con garantía, que es EL caso de uso de los context managers."
    }
  ],
  exercises: [
    {
      id: "adv-proj-1",
      title: "Sistema de biblioteca",
      difficulty: 5,
      prompt: "<p>Implementá el sistema completo:</p><ol><li><code>@dataclass</code> <code>Book</code>: campos <code>title: str</code>, <code>author: str</code>, <code>available: bool = True</code>.</li><li><code>class BookNotAvailable(Exception)</code> — dos líneas, gran API.</li><li><code>class Library</code>:<ul><li><code>__init__</code>: lista interna de libros vacía.</li><li><code>add(book: Book)</code> — agrega.</li><li><code>__len__</code> — cantidad TOTAL de libros (dunder: habilita <code>len(lib)</code>).</li><li><code>borrow(title: str) -&gt; Book</code> — busca por título exacto (insensible a mayúsculas); si no existe o no está disponible → <code>raise BookNotAvailable(title)</code>; si está, lo marca no disponible y lo devuelve.</li><li><code>give_back(title: str)</code> — lo marca disponible de nuevo.</li><li><code>search(term: str)</code> — <strong>generador</strong> que yieldea los libros cuyo título o autor contengan el término (insensible a mayúsculas).</li></ul></li><li><code>class LoanSession</code> — context manager: <code>__init__(self, library)</code>; <code>__enter__</code> devuelve self; método <code>take(title) -&gt; Book</code> que pide prestado vía la library y registra; <code>__exit__</code> devuelve TODO lo registrado (give_back de cada uno), pase lo que pase, sin suprimir excepciones.</li></ol>",
      starter: "from dataclasses import dataclass\nimport types\n\n@dataclass\nclass Book:\n    pass\n\nclass BookNotAvailable(Exception):\n    pass\n\nclass Library:\n    pass\n\nclass LoanSession:\n    pass\n\n# proba mientras desarrollas:\nlib = Library()\nlib.add(Book(\"Dune\", \"Frank Herbert\"))\nlib.add(Book(\"Neuromancer\", \"William Gibson\"))\nlib.add(Book(\"Foundation\", \"Isaac Asimov\"))\nprint(len(lib))\n# b = lib.borrow(\"dune\")\n# print(b)\n",
      tests: "import types as _types\nlib = Library()\nlib.add(Book(\"Dune\", \"Frank Herbert\"))\nlib.add(Book(\"Neuromancer\", \"William Gibson\"))\nlib.add(Book(\"Foundation\", \"Isaac Asimov\"))\nlib.add(Book(\"I, Robot\", \"Isaac Asimov\"))\nassert len(lib) == 4, f\"__len__: {len(lib)}\"\nb = lib.borrow(\"DUNE\")\nassert b.title == \"Dune\" and b.available is False, \"borrow marca no disponible y devuelve el Book\"\ntry:\n    lib.borrow(\"dune\")\n    assert False, \"pedir un libro ya prestado: BookNotAvailable\"\nexcept BookNotAvailable:\n    pass\ntry:\n    lib.borrow(\"inexistente\")\n    assert False, \"pedir un libro que no existe: BookNotAvailable\"\nexcept BookNotAvailable:\n    pass\nlib.give_back(\"dune\")\nassert lib.borrow(\"Dune\").title == \"Dune\", \"tras give_back se puede volver a pedir\"\nlib.give_back(\"dune\")\n_s = lib.search(\"asimov\")\nassert isinstance(_s, _types.GeneratorType), \"search debe ser un GENERADOR (yield)\"\nassert sorted(bk.title for bk in _s) == [\"Foundation\", \"I, Robot\"], \"search por autor, insensible a mayusculas\"\nassert [bk.title for bk in lib.search(\"neuro\")] == [\"Neuromancer\"], \"search por fragmento de titulo\"\nwith LoanSession(lib) as session:\n    bb = session.take(\"foundation\")\n    assert bb.available is False, \"dentro de la sesion, el libro esta prestado\"\nassert next(bk for bk in lib.search(\"foundation\")).available is True, \"al cerrar la sesion, el libro VOLVIO solo\"\ntry:\n    with LoanSession(lib) as session:\n        session.take(\"dune\")\n        session.take(\"neuromancer\")\n        raise RuntimeError(\"el usuario se fue sin avisar\")\nexcept RuntimeError:\n    pass\nassert all(bk.available for bk in lib.search(\"\")), f\"tras la sesion explotada, TODOS los libros deben estar de vuelta\"",
      solution: "from dataclasses import dataclass\n\n@dataclass\nclass Book:\n    title: str\n    author: str\n    available: bool = True\n\nclass BookNotAvailable(Exception):\n    pass\n\nclass Library:\n    def __init__(self):\n        self._books: list[Book] = []\n\n    def add(self, book: Book) -> None:\n        self._books.append(book)\n\n    def __len__(self) -> int:\n        return len(self._books)\n\n    def _find(self, title: str) -> Book | None:\n        for book in self._books:\n            if book.title.lower() == title.lower():\n                return book\n        return None\n\n    def borrow(self, title: str) -> Book:\n        book = self._find(title)\n        if book is None or not book.available:\n            raise BookNotAvailable(title)\n        book.available = False\n        return book\n\n    def give_back(self, title: str) -> None:\n        book = self._find(title)\n        if book is not None:\n            book.available = True\n\n    def search(self, term: str):\n        term = term.lower()\n        for book in self._books:\n            if term in book.title.lower() or term in book.author.lower():\n                yield book\n\nclass LoanSession:\n    def __init__(self, library: Library):\n        self.library = library\n        self.taken: list[Book] = []\n\n    def __enter__(self):\n        return self\n\n    def take(self, title: str) -> Book:\n        book = self.library.borrow(title)\n        self.taken.append(book)\n        return book\n\n    def __exit__(self, exc_type, exc_value, traceback):\n        for book in self.taken:\n            self.library.give_back(book.title)\n        return False",
      explanation: "<p>Recorrido por las decisiones de diseño:</p><p><strong>El helper privado <code>_find</code></strong>: borrow y give_back necesitaban la misma búsqueda — en vez de duplicarla, vive una vez, con guion bajo (convención: \"interno, no es API\"). Devuelve <code>Book | None</code> y cada caller decide qué significa el None para ÉL: borrow lo convierte en excepción (es un error del usuario), give_back lo ignora (devolver algo inexistente es inofensivo). Mismo dato, políticas distintas — por eso _find no decide por ellos.</p><p><strong>borrow unifica dos fallos</strong> (no existe / no disponible) en una sola excepción: para quien pide un libro, la distinción rara vez importa, y la API queda simple. Si importara, harías dos clases de excepción — decisión de diseño, no de sintaxis.</p><p><strong>search como generador</strong> con doble condición — y mirá el test que lo usa: <code>next(bk for bk in lib.search(...))</code>… generadores alimentando generadores, sin una lista a la vista.</p><p><strong>LoanSession</strong> es el broche: registra cada take y su __exit__ devuelve todo — el test de la \"sesión explotada\" verificó que NINGÚN libro quedó huérfano tras el RuntimeError. Garantía estructural, no buena voluntad del usuario.</p><p>Mirá el conjunto: 60 líneas donde cada pieza del nivel hace su trabajo natural. Esto ya no es \"saber Python\" — es diseñar con Python. NumPy te espera.</p>",
      hints: ["Orden sugerido: Book (4 líneas) → BookNotAvailable (2) → Library sin search → tests parciales con Ejecutar → search → LoanSession.", "Escribí un helper _find(title) que devuelva el Book o None: borrow y give_back lo comparten.", "search: for book in self._books: if term in book.title.lower() or term in book.author.lower(): yield book.", "LoanSession.take llama a library.borrow Y guarda el libro en una lista propia; __exit__ recorre esa lista haciendo give_back. Return False (o nada) para no tragar excepciones."]
    }
  ]
}
]);
