/* ============================================================
   INTRO A MACHINE LEARNING: qué es, un modelo simple,
   train/test split y proyecto final
   (usa NumPy: la primera ejecución del nivel lo descarga)
   ============================================================ */
DOJO_PUSH("ml", [

/* ---------------- Qué es ML ---------------- */
{
  id: "ml-intro",
  title: "¿Qué es machine learning?",
  intro: "Programación clásica: vos escribís las reglas. Machine learning: vos das ejemplos y la máquina <strong>encuentra</strong> las reglas — eligiendo, entre muchas funciones posibles, la que menos se equivoca. Este tema desarma esa frase en código: modelo, error, features, baseline y búsqueda.",
  socratic: [
    {
      q: "\"La máquina aprende\" suena místico. En términos de lo que ya sabés — funciones, parámetros, loops — ¿qué es ENTRENAR un modelo?",
      a: "Es buscar números. Un modelo es una función con parámetros libres (en <code>precio = w·area + b</code>, los parámetros son w y b); entrenar es probar valores de esos parámetros y quedarse con los que producen MENOS ERROR sobre los ejemplos. Nada más: una función, una medida de error, y una búsqueda. Todo el deep learning es esta idea con funciones de millones de parámetros y búsquedas más astutas."
    },
    {
      q: "¿Por qué se necesita una MEDIDA de error (como el MSE)? ¿Qué pasaría si solo dijeras \"quiero que prediga bien\"?",
      a: "\"Bien\" no se puede optimizar: la búsqueda necesita comparar dos candidatos y decidir cuál es MEJOR, o sea, un número. El MSE (mean squared error: promedio de los errores al cuadrado) convierte \"qué tan mal predice\" en un escalar comparable. El cuadrado tiene dos gracias: borra el signo (errarle por +5 o −5 pesa igual) y castiga MÁS los errores grandes — un error de 10 pesa como cien errores de 1."
    },
    {
      q: "X mayúscula para las features, y minúscula para el target. ¿Qué son, y por qué la convención de mayúscula/minúscula?",
      a: "Features (X): las variables de ENTRADA con que predecís — superficie, ambientes, edad. Target (y): lo que querés predecir — el precio. La tipografía es información: X es matriz (n_samples × n_features, por eso mayúscula), y es vector (un valor por muestra). Todo dataset supervisado es ese par (X, y): ejemplos de entrada con su respuesta correcta."
    },
    {
      q: "Antes de celebrar un modelo, lo profesional es compararlo contra un \"baseline\" tonto: predecir siempre el promedio. ¿Por qué?",
      a: "Porque los números de error no significan nada en el vacío: ¿MSE de 400 es bueno? Depende — ¿cuánto da predecir la media sin mirar nada? Si tu modelo no le gana CÓMODO al baseline, no aprendió nada útil (o el problema no tiene señal). Es el control de sanidad número uno, y saltearlo es la fuente clásica de modelos \"buenísimos\" que no sirven. La mejora sobre el baseline es la medida honesta del aprendizaje."
    }
  ],
  exercises: [
    {
      id: "ml-intro-1",
      title: "Un modelo es una función con parámetros",
      difficulty: 1,
      prompt: "<p>Una inmobiliaria tasa \"a ojo\": $1200 por metro cuadrado más $50.000 de base. Eso ES un modelo — uno escrito a mano:</p><ul><li><code>w</code> = 1200 y <code>b</code> = 50000 (los <strong>parámetros</strong>: pendiente y ordenada)</li><li><code>areas = np.array([50, 80, 120])</code> — tres casas a tasar</li><li><code>predictions</code>: el precio predicho de las tres, vectorizado: <code>w * areas + b</code> → <code>[110000, 146000, 194000]</code></li></ul><p>Machine learning va a ser exactamente esto, con UNA diferencia: w y b no los va a decidir la inmobiliaria — van a salir de los datos.</p>",
      starter: "import numpy as np\n\nw = 1200\nb = 50000\nareas = np.array([50, 80, 120])\n\n# predictions = ?\n",
      tests: "assert predictions.tolist() == [110000, 146000, 194000], f\"predictions: {predictions}\"",
      solution: "import numpy as np\n\nw = 1200\nb = 50000\nareas = np.array([50, 80, 120])\n\npredictions = w * areas + b",
      explanation: "<p><code>w * areas + b</code> — broadcasting puro: el modelo tasó las tres casas en una expresión, y tasaría tres millones igual. Esta función lineal de una variable es el \"hola mundo\" de los modelos, y su anatomía es universal: <strong>entrada</strong> (area) → <strong>parámetros</strong> (w, b) → <strong>predicción</strong>.</p><p>Quedate con la pregunta incómoda: ¿de dónde salieron el 1200 y el 50000? De la intuición de alguien. ¿Y si el mercado real paga 1850 el metro? El modelo va a tasar mal TODO, sistemáticamente. La promesa del machine learning es reemplazar \"la intuición de alguien\" por \"los valores que mejor explican los datos\" — y para eso, primero necesitamos medir qué tan mal tasa un modelo dado. Siguiente ejercicio.</p>",
      hints: ["Una línea: predictions = w * areas + b — el broadcasting hace el resto."]
    },
    {
      id: "ml-intro-2",
      title: "MSE: el medidor de equivocación",
      difficulty: 2,
      prompt: "<p>Implementá <code>mse(y_true, y_pred)</code>: el promedio de los errores al cuadrado — <code>mean((y_true - y_pred)²)</code> — vectorizado, sin loops.</p><ul><li><code>mse(np.array([3, 5, 2]), np.array([2, 5, 4]))</code> → errores <code>[1, 0, -2]</code>, cuadrados <code>[1, 0, 4]</code>, promedio → <code>1.6667</code></li><li>Predicción perfecta → <code>0.0</code></li></ul><p>Después usala: <code>error_big</code> para un único error de 10 en una muestra (<code>mse([10], [0])</code> como arrays) y <code>error_small</code> para diez errores de 1 (<code>mse(unos*10... pensalo: [1,1,...,1] contra ceros</code>). Compará: ¿cuál \"duele\" más?</p>",
      starter: "import numpy as np\n\ndef mse(y_true, y_pred):\n    pass\n\n# error_big = ?    un solo error de 10\n# error_small = ?  diez errores de 1\n",
      tests: "import numpy as _np\nassert abs(mse(_np.array([3, 5, 2]), _np.array([2, 5, 4])) - 5/3) < 1e-9, f\"mse basico: {mse(_np.array([3, 5, 2]), _np.array([2, 5, 4]))}\"\nassert mse(_np.array([7.0, 7.0]), _np.array([7.0, 7.0])) == 0.0, \"prediccion perfecta: MSE 0\"\nassert abs(error_big - 100.0) < 1e-9, f\"error_big: {error_big}\"\nassert abs(error_small - 1.0) < 1e-9, f\"error_small: {error_small}\"",
      solution: "import numpy as np\n\ndef mse(y_true, y_pred):\n    return ((y_true - y_pred) ** 2).mean()\n\nerror_big = mse(np.array([10.0]), np.array([0.0]))\nerror_small = mse(np.ones(10), np.zeros(10))",
      explanation: "<p>Una línea de NumPy: resta vectorizada → cuadrado elemento a elemento → media. Esta funcioncita va a ser tu juez en TODO lo que sigue: cada decisión de entrenamiento se tomará \"porque baja el MSE\".</p><p>La comparación final es la personalidad del MSE en números: un error de 10 pesa 100; diez errores de 1 pesan 1. <strong>El cuadrado odia los errores grandes</strong> — un modelo entrenado con MSE prefiere equivocarse poquito en todos lados antes que mucho en un caso. ¿Es siempre lo que querés? No: si tus datos tienen outliers salvajes, ese odio se vuelve obsesión y el modelo se distorsiona por complacerlos (para eso existe el MAE, error absoluto, más tolerante). Elegir la medida de error ES una decisión de diseño — la primera de todo proyecto de ML.</p>",
      hints: ["return ((y_true - y_pred) ** 2).mean() — resta, cuadrado, media: todo vectorizado.", "error_small: np.ones(10) contra np.zeros(10)."]
    },
    {
      id: "ml-intro-3",
      title: "X e y: anatomía de un dataset",
      difficulty: 3,
      prompt: "<p>Te llega un dataset crudo de casas — una matriz donde cada FILA es una casa y las columnas son <code>[superficie, ambientes, precio]</code>:</p><pre>data = np.array([[50, 2, 120],\n                 [80, 3, 200],\n                 [120, 4, 310],\n                 [60, 2, 150]])</pre><p>Separalo en features y target con slicing de NumPy (¡tema del nivel pasado!):</p><ul><li><code>X</code>: TODAS las filas, las primeras 2 columnas (superficie y ambientes) → shape <code>(4, 2)</code></li><li><code>y</code>: la última columna (el precio) → shape <code>(4,)</code></li><li><code>n_samples</code> y <code>n_features</code>: extraelas de <code>X.shape</code> por unpacking</li><li><code>first_house</code>: las features de la primera casa → <code>[50, 2]</code></li></ul>",
      starter: "import numpy as np\n\ndata = np.array([[50, 2, 120],\n                 [80, 3, 200],\n                 [120, 4, 310],\n                 [60, 2, 150]])\n\n# X = ?\n# y = ?\n# n_samples, n_features = ?\n# first_house = ?\n",
      tests: "assert X.shape == (4, 2), f\"X.shape: {X.shape}\"\nassert X.tolist() == [[50, 2], [80, 3], [120, 4], [60, 2]], f\"X: {X}\"\nassert y.tolist() == [120, 200, 310, 150], f\"y: {y}\"\nassert y.shape == (4,), f\"y.shape: {y.shape} — la ultima columna como vector, no como matriz\"\nassert n_samples == 4 and n_features == 2, f\"n_samples={n_samples}, n_features={n_features}\"\nassert first_house.tolist() == [50, 2], f\"first_house: {first_house}\"",
      solution: "import numpy as np\n\ndata = np.array([[50, 2, 120],\n                 [80, 3, 200],\n                 [120, 4, 310],\n                 [60, 2, 150]])\n\nX = data[:, :2]\ny = data[:, -1]\nn_samples, n_features = X.shape\nfirst_house = X[0]",
      explanation: "<p>Dos slices y el dataset quedó en la forma canónica que TODA librería de ML espera: <code>X</code> de shape <code>(n_samples, n_features)</code> — cada fila una observación, cada columna una variable — e <code>y</code> de shape <code>(n_samples,)</code>, la respuesta correcta de cada fila. Cuando llegues a scikit-learn, <code>model.fit(X, y)</code> pide EXACTAMENTE estos dos objetos con estas shapes.</p><p>El detalle de <code>data[:, -1]</code> vs <code>data[:, -1:]</code>: sin los dos puntos finales, el eje se colapsa y obtenés el vector (4,) que corresponde; con ellos, una matriz columna (4,1) que rompe medio scikit-learn con warnings crípticos. Las shapes importan — el diagnóstico de la mitad de los errores de ML empieza imprimiéndolas.</p><p>(El unpacking de <code>X.shape</code> es la tupla de siempre abriéndose en dos nombres: Básico sigue pagando dividendos.)</p>",
      hints: ["X: data[:, :2] — todas las filas, columnas 0 y 1. y: data[:, -1].", "n_samples, n_features = X.shape — unpacking de la tupla shape."]
    },
    {
      id: "ml-intro-4",
      title: "El baseline: gana o no jugaste",
      difficulty: 4,
      prompt: "<p>Mediste la temperatura de un proceso 5 días: <code>y = np.array([10.0, 12.0, 11.0, 9.0, 13.0])</code>. Un colega presume de su modelo, que predijo <code>model_preds = np.array([9.5, 12.5, 10.5, 9.5, 12.5])</code>. ¿Es bueno? Auditalo:</p><ul><li><code>baseline_pred</code>: la predicción \"tonta\" — un array de 5 valores todos iguales a la MEDIA de y (<code>np.full(5, valor)</code> o broadcasting con ones)</li><li><code>baseline_mse</code>: el MSE del baseline → <code>2.0</code> (reusá tu mse o reescribila)</li><li><code>model_mse</code>: el MSE del modelo del colega → <code>0.25</code></li><li><code>is_better</code>: ¿el modelo le gana al baseline? (booleano)</li><li><code>improvement</code>: cuántas veces mejor: baseline/model → <code>8.0</code></li></ul>",
      starter: "import numpy as np\n\ny = np.array([10.0, 12.0, 11.0, 9.0, 13.0])\nmodel_preds = np.array([9.5, 12.5, 10.5, 9.5, 12.5])\n\ndef mse(y_true, y_pred):\n    return ((y_true - y_pred) ** 2).mean()\n\n# baseline_pred = ?\n# baseline_mse = ?\n# model_mse = ?\n# is_better = ?\n# improvement = ?\n",
      tests: "import numpy as _np\nassert baseline_pred.tolist() == [11.0] * 5, f\"baseline_pred: {baseline_pred}\"\nassert abs(baseline_mse - 2.0) < 1e-9, f\"baseline_mse: {baseline_mse}\"\nassert abs(model_mse - 0.25) < 1e-9, f\"model_mse: {model_mse}\"\nassert bool(is_better) is True, f\"is_better: {is_better}\"\nassert abs(improvement - 8.0) < 1e-9, f\"improvement: {improvement}\"",
      solution: "import numpy as np\n\ny = np.array([10.0, 12.0, 11.0, 9.0, 13.0])\nmodel_preds = np.array([9.5, 12.5, 10.5, 9.5, 12.5])\n\ndef mse(y_true, y_pred):\n    return ((y_true - y_pred) ** 2).mean()\n\nbaseline_pred = np.full(5, y.mean())\nbaseline_mse = mse(y, baseline_pred)\nmodel_mse = mse(y, model_preds)\nis_better = model_mse < baseline_mse\nimprovement = baseline_mse / model_mse",
      explanation: "<p>Dato curioso con nombre propio: el MSE de \"predecir siempre la media\" ES la <strong>varianza</strong> de los datos — la media es, matemáticamente, la constante que minimiza el MSE. O sea: el baseline de la media no es cualquier tontería, es LA MEJOR predicción posible si no mirás ninguna feature. Por eso es la vara justa.</p><p>El veredicto del colega: 8 veces mejor que no mirar nada — su modelo SÍ extrajo señal. Esta razón (1 − model/baseline, técnicamente) es la esencia del <em>R²</em> que reportan todos los papers: \"qué fracción de la varianza explica el modelo\".</p><p>Grabate el ritual, porque es profesional de verdad: <strong>antes de evaluar cualquier modelo, calculá el baseline</strong>. Un MSE de 0.25 no significa nada solo; contra 2.0 de baseline, significa todo. Y cuando un modelo NO le gana a la media… también es información: no hay señal, o hay bug.</p>",
      hints: ["baseline_pred: np.full(5, y.mean()) — cinco copias de la media.", "Las dos MSE con tu función; is_better es la comparación; improvement, la división."]
    },
    {
      id: "ml-intro-5",
      title: "Entrenar = buscar: grid search a mano",
      difficulty: 5,
      prompt: "<p>Tu primer ENTRENAMIENTO, con la búsqueda más honesta que existe: probar todo. El starter genera datos con una relación oculta (w=3, b=7) más ruido. Encontrala:</p><ul><li>Candidatos: <code>ws = [1, 2, 3, 4]</code> y <code>bs = [5, 6, 7, 8, 9]</code> — 20 modelos posibles</li><li>Con dos loops anidados, calculá el MSE de CADA par (w, b) sobre los datos: predicciones <code>w * x + b</code>, error contra <code>y_obs</code></li><li>Patrón \"mejor hasta ahora\" (¡el de Básico!): quedate con <code>best_w</code>, <code>best_b</code>, <code>best_mse</code></li></ul><p>Si la búsqueda funciona, debería redescubrir los parámetros verdaderos a pesar del ruido.</p>",
      starter: "import numpy as np\n\nnp.random.seed(1)\nx = np.arange(6).astype(float)          # [0, 1, 2, 3, 4, 5]\ny_obs = 3 * x + 7 + np.random.randn(6) * 0.5   # la verdad + ruido\n\nws = [1, 2, 3, 4]\nbs = [5, 6, 7, 8, 9]\n\ndef mse(y_true, y_pred):\n    return ((y_true - y_pred) ** 2).mean()\n\n# best_w, best_b, best_mse = ?\n",
      tests: "assert best_w == 3, f\"best_w: {best_w} — la busqueda deberia redescubrir w=3\"\nassert best_b == 7, f\"best_b: {best_b}\"\nassert best_mse < 1.0, f\"best_mse: {best_mse} — con los parametros correctos, solo queda el ruido\"\nimport numpy as _np\n_preds = best_w * x + best_b\nassert abs(mse(y_obs, _preds) - best_mse) < 1e-9, \"best_mse debe corresponder al par (best_w, best_b)\"",
      solution: "import numpy as np\n\nnp.random.seed(1)\nx = np.arange(6).astype(float)\ny_obs = 3 * x + 7 + np.random.randn(6) * 0.5\n\nws = [1, 2, 3, 4]\nbs = [5, 6, 7, 8, 9]\n\ndef mse(y_true, y_pred):\n    return ((y_true - y_pred) ** 2).mean()\n\nbest_w, best_b, best_mse = None, None, float(\"inf\")\nfor w in ws:\n    for b in bs:\n        error = mse(y_obs, w * x + b)\n        if error < best_mse:\n            best_w, best_b, best_mse = w, b, error",
      explanation: "<p>Pará y mirá lo que acaba de pasar: <strong>el programa encontró los parámetros sin que nadie se los dijera</strong>. Probó 20 hipótesis, midió cada una contra la realidad, se quedó con la mejor — y la mejor resultó ser la verdad subyacente (w=3, b=7), recuperada a través del ruido. ESO es machine learning. Todo lo demás son refinamientos.</p><p>Las piezas, todas viejas conocidas: loops anidados (Básico), \"mejor hasta ahora\" inicializado en infinito (<code>float(\"inf\")</code>: el truco para que el primer candidato siempre gane), MSE como juez, vectorización para evaluar cada hipótesis de un golpe.</p><p>La limitación también es visible: 2 parámetros × pocos candidatos = 20 evaluaciones. Una red neuronal tiene millones de parámetros CONTINUOS — la grilla explota combinatoriamente. Por eso existe el <em>gradiente</em>: en vez de probar a ciegas, preguntarle al error \"¿hacia dónde bajo?\". Próximo tema. (Pero el grid search no es juguete: los <em>hiperparámetros</em> de los modelos reales se buscan exactamente así.)</p>",
      hints: ["Arrancá con best_mse = float(\"inf\") — así el primer candidato siempre entra.", "for w in ws: / for b in bs: / calcular mse de w*x+b / si mejora, guardar los tres.", "El error se calcula contra y_obs (lo observado), no contra la fórmula verdadera — esa no la conocés en la vida real."]
    }
  ]
},

/* ---------------- Modelo simple ---------------- */
{
  id: "ml-model",
  title: "Tu primer modelo: regresión lineal",
  intro: "Regresión lineal: la recta que mejor atraviesa los datos. La vas a entrenar DOS veces — con la fórmula exacta y con <strong>gradient descent</strong>, el motor que (a otra escala) entrena ChatGPT. Sin librerías de ML: NumPy y tus manos.",
  socratic: [
    {
      q: "¿Por qué los datos sintéticos (generados por vos, con seed) son la herramienta correcta para APRENDER ML, antes que datos reales?",
      a: "Porque conocés la respuesta correcta: si generaste y = 2.5x + 10 + ruido, sabés que el entrenamiento DEBE recuperar ~2.5 y ~10 — tenés con qué verificar. Con datos reales nunca sabés si un mal resultado es bug tuyo o ruido del mundo. Es el mismo principio de tus tests de toda la herramienta: primero validá la maquinaria donde conocés la verdad; después soltala en lo desconocido. Los papers serios hacen exactamente esto (sanity checks con datos sintéticos)."
    },
    {
      q: "La fórmula cerrada da la respuesta exacta en un paso: w = cov(x,y)/var(x). Si existe… ¿para qué aprender gradient descent?",
      a: "Porque la fórmula cerrada es un lujo de los problemas lineales chicos: existe solo para mínimos cuadrados, y con millones de features hasta ella se vuelve impracticable (invertir matrices gigantes). Gradient descent es el método UNIVERSAL: funciona para cualquier modelo derivable — redes neuronales incluidas, donde ninguna fórmula cerrada existe. Aprendés la cerrada como verdad de referencia, y GD como el motor real."
    },
    {
      q: "El gradiente del error apunta \"hacia donde el error crece más rápido\". ¿Por qué entonces el update es restar: w = w − lr·gradiente?",
      a: "Porque querés BAJAR el error, no subirlo: te movés en contra del gradiente — de ahí \"descent\". La intuición de la montaña a ciegas: el gradiente te dice hacia dónde está la subida más empinada; caminás exactamente al revés, un pasito (lr) por vez, y terminás en el valle. Cada parámetro recibe su propia componente del gradiente: w y b bajan cada uno por su dimensión."
    },
    {
      q: "El learning rate es \"el tamaño del paso\". ¿Qué pasa si es demasiado chico? ¿Y demasiado grande?",
      a: "Chico: convergés a paso de tortuga — mil épocas para lo que debían ser cien (costo, no tragedia). Grande: te pasás de largo del valle, rebotás cada vez más alto y el error DIVERGE a infinito (tragedia: el entrenamiento explota, verás NaNs). El lr es el hiperparámetro más sensible del deep learning, y elegirlo es parte arte: típicamente se prueban potencias de 10 y se observa la curva de pérdida."
    }
  ],
  exercises: [
    {
      id: "ml-model-1",
      title: "Fabricar el dataset",
      difficulty: 1,
      prompt: "<p>Generá el dataset con que vas a trabajar TODO el tema: 80 casas, superficie vs precio (en miles). La relación verdadera — que el modelo deberá redescubrir — es <code>y = 2.5x + 10</code> más ruido gaussiano:</p><ol><li><code>np.random.seed(42)</code> — reproducibilidad ante todo</li><li><code>x</code>: 80 superficies uniformes entre 0 y 10: <code>np.random.rand(80) * 10</code></li><li><code>noise</code>: 80 valores gaussianos: <code>np.random.randn(80)</code></li><li><code>y</code>: <code>2.5 * x + 10 + noise</code></li></ol><p>El ORDEN de las llamadas random importa (la semilla genera una secuencia): rand primero, randn después, o los tests no van a coincidir.</p>",
      starter: "import numpy as np\n\n# 1. semilla\n# 2. x = ?\n# 3. noise = ?\n# 4. y = ?\n\n# print(x[:5])\n# print(y[:5])\n",
      tests: "import numpy as _np\n_np.random.seed(42)\n_x = _np.random.rand(80) * 10\n_noise = _np.random.randn(80)\n_y = 2.5 * _x + 10 + _noise\nassert x.shape == (80,), f\"x.shape: {x.shape}\"\nassert _np.allclose(x, _x), \"x no coincide: ¿seed(42) ANTES de rand? ¿rand(80) * 10?\"\nassert _np.allclose(y, _y), \"y no coincide: el orden es seed -> rand -> randn, y la formula 2.5*x + 10 + noise\"",
      solution: "import numpy as np\n\nnp.random.seed(42)\nx = np.random.rand(80) * 10\nnoise = np.random.randn(80)\ny = 2.5 * x + 10 + noise",
      explanation: "<p>Acabás de hacer lo que hace cada tutorial y cada test de librería de ML: un mundo de juguete donde la verdad es conocida — pendiente 2.5, ordenada 10, ruido de desvío 1. En los próximos ejercicios, cuando el entrenamiento devuelva w≈2.5, vas a SABER que funciona — ese es el lujo del dato sintético.</p><p>Los dos generadores que usaste son la pareja estándar: <code>rand</code> (uniforme en [0,1), escalado a tu rango — las superficies) y <code>randn</code> (gaussiana centrada en 0, desvío 1 — el ruido, porque el ruido del mundo real tiende a ser gaussiano: suma de mil factores chicos). Y la semilla, tu vieja amiga de Intermedio, ahora en su rol profesional: el experimento entero será bit a bit reproducible.</p>",
      hints: ["El orden exacto: np.random.seed(42), después x = np.random.rand(80) * 10, después noise = np.random.randn(80).", "y = 2.5 * x + 10 + noise — la relación verdadera más el ruido."]
    },
    {
      id: "ml-model-2",
      title: "predict y el error inicial",
      difficulty: 2,
      prompt: "<p>Las dos funciones de infraestructura (van a sobrevivir hasta el proyecto final):</p><ul><li><code>predict(x, w, b)</code> → <code>w * x + b</code> (vectorizada gratis)</li><li><code>mse(y_true, y_pred)</code> → la de siempre</li></ul><p>Y usalas para medir el punto de partida sobre el dataset del starter:</p><ul><li><code>mse_zero</code>: el error del modelo \"recién nacido\" w=0, b=0 (predice 0 para todo) → un número ENORME</li><li><code>mse_true</code>: el error con los parámetros verdaderos w=2.5, b=10 → cerca de <code>1.0</code> (¿por qué 1? ¿qué queda cuando el modelo es perfecto?)</li></ul>",
      starter: "import numpy as np\n\nnp.random.seed(42)\nx = np.random.rand(80) * 10\ny = 2.5 * x + 10 + np.random.randn(80)\n\ndef predict(x, w, b):\n    pass\n\ndef mse(y_true, y_pred):\n    pass\n\n# mse_zero = ?\n# mse_true = ?\n",
      tests: "import numpy as _np\nassert _np.allclose(predict(_np.array([1.0, 2.0]), 3, 1), [4.0, 7.0]), \"predict(x, 3, 1) sobre [1,2] debe dar [4,7]\"\nassert mse(_np.array([1.0]), _np.array([1.0])) == 0.0\nassert mse_zero > 300, f\"mse_zero: {mse_zero} — con w=b=0 el error debe ser enorme\"\nassert 0.5 < mse_true < 1.6, f\"mse_true: {mse_true} — con los parametros verdaderos solo queda el ruido (~1)\"",
      solution: "import numpy as np\n\nnp.random.seed(42)\nx = np.random.rand(80) * 10\ny = 2.5 * x + 10 + np.random.randn(80)\n\ndef predict(x, w, b):\n    return w * x + b\n\ndef mse(y_true, y_pred):\n    return ((y_true - y_pred) ** 2).mean()\n\nmse_zero = mse(y, predict(x, 0, 0))\nmse_true = mse(y, predict(x, 2.5, 10))",
      explanation: "<p>Dos números que enmarcan todo el tema: <code>mse_zero</code> (≈560) es el punto de partida del modelo ignorante; <code>mse_true</code> (≈1) es EL PISO — y la respuesta a la pregunta del enunciado: aunque el modelo sea PERFECTO, el error no llega a cero, porque los datos traen ruido irreducible (generaste y con randn de varianza 1: ahí está tu ≈1). Ningún entrenamiento honesto puede bajar de ahí — si algo te da menos, sospechá (suele ser trampa: evaluar sobre lo memorizado, tema del próximo capítulo).</p><p>Todo el trabajo que sigue — fórmula cerrada, gradientes, épocas — es el viaje de 560 a 1. Tener el piso y el techo ANTES de entrenar es otra forma del hábito baseline: sin referencia, los números de error son astrología.</p>",
      hints: ["predict: return w * x + b. mse: la de siempre.", "mse_zero = mse(y, predict(x, 0, 0)) — y lo mismo con 2.5 y 10."]
    },
    {
      id: "ml-model-3",
      title: "La fórmula cerrada",
      difficulty: 3,
      prompt: "<p>Para la regresión lineal simple, el mejor (w, b) tiene fórmula exacta — la covarianza sobre la varianza:</p><pre>w = mean((x - x̄) · (y - ȳ)) / mean((x - x̄)²)\nb = ȳ - w · x̄</pre><p>Implementala con NumPy sobre el dataset del starter:</p><ul><li><code>x_mean</code>, <code>y_mean</code></li><li><code>w_hat</code>: la fórmula de arriba, vectorizada (las dos medias de productos)</li><li><code>b_hat</code>: despejada de que la recta pasa por el punto promedio</li><li><code>fitted_mse</code>: el MSE con estos parámetros — debería pegarse al piso (~1) del ejercicio anterior</li></ul><p>¿Recuperó la verdad (2.5 y 10)? Imprimilos.</p>",
      starter: "import numpy as np\n\nnp.random.seed(42)\nx = np.random.rand(80) * 10\ny = 2.5 * x + 10 + np.random.randn(80)\n\ndef mse(y_true, y_pred):\n    return ((y_true - y_pred) ** 2).mean()\n\n# x_mean, y_mean = ?\n# w_hat = ?\n# b_hat = ?\n# fitted_mse = ?\n\n# print(w_hat, b_hat)\n",
      tests: "import numpy as _np\n_xm, _ym = x.mean(), y.mean()\n_w = ((x - _xm) * (y - _ym)).mean() / ((x - _xm) ** 2).mean()\n_b = _ym - _w * _xm\nassert abs(w_hat - _w) < 1e-9, f\"w_hat: {w_hat} — revisa la formula: mean((x-xm)*(y-ym)) / mean((x-xm)**2)\"\nassert abs(b_hat - _b) < 1e-9, f\"b_hat: {b_hat}\"\nassert 2.3 < w_hat < 2.7, f\"w_hat deberia rondar 2.5: {w_hat}\"\nassert 9.0 < b_hat < 11.0, f\"b_hat deberia rondar 10: {b_hat}\"\nassert fitted_mse < 1.3, f\"fitted_mse: {fitted_mse} — el ajuste optimo se pega al piso del ruido\"",
      solution: "import numpy as np\n\nnp.random.seed(42)\nx = np.random.rand(80) * 10\ny = 2.5 * x + 10 + np.random.randn(80)\n\ndef mse(y_true, y_pred):\n    return ((y_true - y_pred) ** 2).mean()\n\nx_mean = x.mean()\ny_mean = y.mean()\n\nw_hat = ((x - x_mean) * (y - y_mean)).mean() / ((x - x_mean) ** 2).mean()\nb_hat = y_mean - w_hat * x_mean\n\nfitted_mse = mse(y, w_hat * x + b_hat)",
      explanation: "<p>Mirá los números que imprimiste: w≈2.48, b≈10.1 — la verdad (2.5, 10) recuperada de datos ruidosos por una fórmula de dos líneas. La intuición de la fórmula: la covarianza del numerador mide \"cuándo x sube, ¿y sube?\"; la varianza del denominador normaliza por cuánto se mueve x — el cociente es \"cuántas unidades de y por unidad de x\": la pendiente. Y b se despeja de un hecho elegante: la recta óptima SIEMPRE pasa por el punto promedio (x̄, ȳ).</p><p>Esto es exactamente lo que hace <code>LinearRegression().fit()</code> de scikit-learn (en su versión multivariable, la ecuación normal con la matriz de Gram que viste en NumPy). Ya no es magia: es esta celda.</p><p>Guardá <code>fitted_mse</code> ≈ 0.93: es la vara contra la que vas a juzgar al gradient descent — que debe llegar al MISMO destino por un camino completamente distinto.</p>",
      hints: ["Centrá primero: dx = x - x_mean, dy = y - y_mean. Entonces w_hat = (dx * dy).mean() / (dx ** 2).mean().", "b_hat = y_mean - w_hat * x_mean — la recta pasa por el punto promedio."]
    },
    {
      id: "ml-model-4",
      title: "El gradiente: un paso cuesta abajo",
      difficulty: 4,
      prompt: "<p>Ahora el camino universal. Para el MSE, el cálculo (hecho en pizarrón por vos algún día; hoy te lo doy) dice que las derivadas parciales son:</p><pre>dw = 2 · mean((pred − y) · x)\ndb = 2 · mean(pred − y)</pre><p>Desde w=0, b=0, dá UN paso:</p><ol><li><code>preds0</code> y <code>mse0</code>: predicciones y error en el punto de partida</li><li><code>dw</code> y <code>db</code>: el gradiente ahí (¿qué SIGNO esperás? El modelo predice 0 y la verdad es positiva → pred−y negativo → …)</li><li>Con <code>lr = 0.01</code>: <code>w1 = 0 - lr * dw</code> y <code>b1</code> análogo</li><li><code>mse1</code>: el error después del paso. La única promesa del gradiente: <code>mse1 &lt; mse0</code>.</li></ol>",
      starter: "import numpy as np\n\nnp.random.seed(42)\nx = np.random.rand(80) * 10\ny = 2.5 * x + 10 + np.random.randn(80)\n\ndef mse(y_true, y_pred):\n    return ((y_true - y_pred) ** 2).mean()\n\nlr = 0.01\n\n# preds0, mse0 = ?\n# dw, db = ?\n# w1, b1 = ?\n# mse1 = ?\n\n# print(mse0, \"->\", mse1)\n",
      tests: "import numpy as _np\nassert abs(mse0 - (y ** 2).mean()) < 1e-9, f\"mse0: {mse0} — con w=b=0, las predicciones son todas 0\"\n_dw = 2 * ((0 * x + 0 - y) * x).mean()\n_db = 2 * (0 * x + 0 - y).mean()\nassert abs(dw - _dw) < 1e-6, f\"dw: {dw} — formula: 2 * mean((pred - y) * x)\"\nassert abs(db - _db) < 1e-6, f\"db: {db}\"\nassert dw < 0 and db < 0, \"ambos gradientes deben ser NEGATIVOS aca: el modelo predice de menos\"\nassert w1 > 0 and b1 > 0, \"restar un gradiente negativo MUEVE los parametros hacia arriba\"\nassert mse1 < mse0, f\"mse1 ({mse1}) debe ser menor que mse0 ({mse0}): esa es LA promesa del gradiente\"",
      solution: "import numpy as np\n\nnp.random.seed(42)\nx = np.random.rand(80) * 10\ny = 2.5 * x + 10 + np.random.randn(80)\n\ndef mse(y_true, y_pred):\n    return ((y_true - y_pred) ** 2).mean()\n\nlr = 0.01\n\npreds0 = np.zeros(80)            # w=0, b=0\nmse0 = mse(y, preds0)\n\nerrors = preds0 - y\ndw = 2 * (errors * x).mean()\ndb = 2 * errors.mean()\n\nw1 = 0 - lr * dw\nb1 = 0 - lr * db\n\nmse1 = mse(y, w1 * x + b1)",
      explanation: "<p>Leé el gradiente como información, no como fórmula: <code>pred − y</code> es \"cuánto me pasé\" en cada punto — acá todo negativo (el modelo predice 0, la verdad ronda 10-35: se queda CORTO en todo). <code>db</code> promedia esos déficits: \"en general, tirás bajo → subí b\". <code>dw</code> los pondera por x: \"te quedás MÁS corto donde x es grande → eso es pendiente que falta → subí w\". El gradiente es el error transformado en instrucciones.</p><p>Y el signo cierra la lógica que predijiste: gradientes negativos (el error BAJA si los parámetros suben), restarlos los vuelve positivos — el paso fue hacia arriba, donde había que ir. mse0 ≈ 560 → mse1 ≈ 80: un paso, 85% del error eliminado (los primeros pasos son los más jugosos: la pendiente es brutal lejos del valle).</p><p>Esto que hiciste a mano — calcular gradiente, dar el paso — es lo que PyTorch automatiza con <code>loss.backward()</code> y <code>optimizer.step()</code>. Misma matemática, mil millones de parámetros.</p>",
      hints: ["preds0 con w=b=0 son 80 ceros: np.zeros(80) o 0 * x + 0.", "errors = preds0 - y; dw = 2 * (errors * x).mean(); db = 2 * errors.mean().", "El update RESTA: w1 = 0 - lr * dw. Si tu mse1 subió, sumaste."]
    },
    {
      id: "ml-model-5",
      title: "El loop de entrenamiento",
      difficulty: 5,
      prompt: "<p>Un paso fue bueno; ahora dale 500. Escribí EL training loop — la estructura más famosa del machine learning:</p><ol><li>Inicializá <code>w = 0.0</code>, <code>b = 0.0</code>, <code>lr = 0.02</code>, y una lista <code>history</code></li><li>500 épocas: calcular predicciones → calcular mse y appendearlo a history → calcular dw, db → actualizar w y b</li><li>Al final: <code>final_mse = history[-1]</code></li></ol><p>Criterios de éxito (los tests): w ≈ 2.5, b ≈ 10 — el MISMO destino que la fórmula cerrada — y una history que solo baja. Imprimí <code>history[0]</code>, <code>history[10]</code>, <code>history[100]</code>, <code>history[-1]</code> para ver la curva de aprendizaje en números.</p>",
      starter: "import numpy as np\n\nnp.random.seed(42)\nx = np.random.rand(80) * 10\ny = 2.5 * x + 10 + np.random.randn(80)\n\nw = 0.0\nb = 0.0\nlr = 0.02\nhistory = []\n\n# for epoch in range(500):\n#     ...\n\n# final_mse = ?\n# print(history[0], history[10], history[100], history[-1])\n",
      tests: "assert len(history) == 500, f\"history debe tener 500 entradas, tiene {len(history)}\"\nassert 2.3 < w < 2.7, f\"w final: {w} — deberia converger cerca de 2.5\"\nassert 8.5 < b < 11.5, f\"b final: {b} — deberia converger cerca de 10\"\nassert final_mse < 1.5, f\"final_mse: {final_mse} — deberia acercarse al piso del ruido (~1)\"\nassert history[0] > 100, \"la primera epoca arranca con error gigante\"\nassert history[0] > history[10] > history[100] > history[-1], \"la curva de perdida debe DESCENDER\"",
      solution: "import numpy as np\n\nnp.random.seed(42)\nx = np.random.rand(80) * 10\ny = 2.5 * x + 10 + np.random.randn(80)\n\nw = 0.0\nb = 0.0\nlr = 0.02\nhistory = []\n\nfor epoch in range(500):\n    preds = w * x + b\n    history.append(((preds - y) ** 2).mean())\n    errors = preds - y\n    dw = 2 * (errors * x).mean()\n    db = 2 * errors.mean()\n    w = w - lr * dw\n    b = b - lr * db\n\nfinal_mse = history[-1]",
      explanation: "<p>Mirá los números que imprimiste: ~560 → ~8 → ~1.5 → ~0.95. Esa secuencia — desplome inicial, refinamiento, meseta en el piso del ruido — es LA curva de pérdida, la imagen que vas a mirar mil veces en tu vida de ML (en TensorBoard, en wandb, en papers). Ya sabés leerla: si no baja, lr muy chico o bug; si explota, lr grande; si baja y se aplana, convergencia.</p><p>Y el resultado final: w≈2.49, b≈9.9 — <strong>el mismo destino que la fórmula cerrada</strong>, alcanzado a pasitos ciegos en vez de por teletransporte algebraico. Esa coincidencia es el punto del tema entero: GD funciona, y funciona TAMBIÉN donde no hay fórmula — que es en todos lados (redes, embeddings, transformers).</p><p>El esqueleto que acabás de escribir — <em>forward (predecir) → loss (medir) → backward (gradientes) → update (paso)</em> — es literalmente el cuerpo del loop de PyTorch. Cuando lo veas allá, vas a reconocer cada línea. Falta una sola pieza del oficio: saber si el modelo aprendió DE VERDAD o memorizó. Último tema.</p>",
      hints: ["Adentro del for, en orden: preds → history.append(mse) → errors → dw, db → w -= lr*dw, b -= lr*db.", "Las fórmulas de dw y db son las del ejercicio anterior, recalculadas con el w y b ACTUALES en cada vuelta.", "¿history sube o da NaN? Revisá el signo del update (restar) o el orden (gradientes ANTES de actualizar)."]
    }
  ]
},

/* ---------------- Train/test split ---------------- */
{
  id: "ml-split",
  title: "Train/test split y generalización",
  intro: "La pregunta que separa ML de estadística de juguete: ¿el modelo <strong>aprendió el patrón</strong> o <strong>memorizó los ejemplos</strong>? La única forma de saberlo: esconderle datos y examinarlo con lo que nunca vio.",
  socratic: [
    {
      q: "¿Por qué evaluar un modelo con los MISMOS datos con que lo entrenaste es hacerse trampa al solitario?",
      a: "Porque mide la habilidad equivocada: recordar, no generalizar. Es darle al alumno el examen con las respuestas que ya practicó — un 10 que no dice nada sobre el examen nuevo. Un modelo con suficiente capacidad puede clavar error CERO en lo visto (memoria pura) y ser inútil en lo nuevo. El error de entrenamiento es sistemáticamente optimista; el único número honesto sale de datos que el modelo jamás tocó."
    },
    {
      q: "¿Por qué el split se hace BARAJANDO (permutación aleatoria) en vez de cortar \"los primeros 80% / los últimos 20%\"?",
      a: "Porque los datos casi nunca vienen en orden neutro: cargados por fecha, agrupados por categoría, ordenados por tamaño… Cortar sin barajar puede dejar todo un tipo de casos fuera del entrenamiento (entrenaste con casas chicas, evaluás con grandes: desastre, y no por culpa del modelo). La permutación aleatoria — con semilla, para reproducir — reparte todo tipo de casos en ambos lados. (Excepción importante que verás algún día: series temporales, donde barajar sería hacer trampa con el futuro.)"
    },
    {
      q: "Eso de \"memorizar\" suena abstracto. ¿Podés imaginar un modelo CONCRETO que memorice perfecto y generalice mal?",
      a: "El \"modelo loro\": guardá la tabla (x, y) completa de entrenamiento; ante una consulta, buscá el x guardado más cercano y devolvé SU y. Error de entrenamiento: exactamente cero (cada x se encuentra a sí mismo). Error en datos nuevos: malo — devuelve el y de otro punto, con su ruido incluido, sin haber destilado ninguna regla. Ese modelo existe, lo vas a construir en este tema, y verlo fallar te va a enseñar más sobre overfitting que cualquier definición."
    },
    {
      q: "Para un clasificador, el accuracy es \"la fracción que acertó\". ¿Con qué idiom de NumPy que YA escribiste se calcula? ¿Y cuándo el accuracy engaña?",
      a: "<code>(predicciones == reales).mean()</code> — la media de una máscara booleana, tu viejo conocido. Engaña con clases desbalanceadas: si el 99% de los mails son legítimos, el clasificador \"todo es legítimo\" tiene 99% de accuracy y cero utilidad — otra vez el baseline como vara: acá el baseline es \"predecir siempre la clase mayoritaria\", y hay que ganarle a ESO. (Para desbalances serios existen precision/recall, tema para tu siguiente curso.)"
    }
  ],
  exercises: [
    {
      id: "ml-split-1",
      title: "Barajar y cortar",
      difficulty: 1,
      prompt: "<p>La mecánica del split, con 10 elementos para verla entera:</p><ol><li><code>np.random.seed(0)</code> y generá <code>shuffled = np.random.permutation(10)</code> — los índices 0-9 barajados. Imprimilos.</li><li><code>test_idx</code>: los primeros 2 índices barajados (20% de test)</li><li><code>train_idx</code>: el resto (8)</li><li><code>overlap</code>: ¿cuántos índices comparten? Convertí ambos a <code>set</code> y usá <code>&amp;</code> (intersección — ¡de Básico!): <code>len(set(...) &amp; set(...))</code> → DEBE ser 0</li></ol>",
      starter: "import numpy as np\n\nnp.random.seed(0)\n\n# shuffled = ?\n# test_idx = ?\n# train_idx = ?\n# overlap = ?\n",
      tests: "import numpy as _np\n_np.random.seed(0)\n_expected = _np.random.permutation(10)\nassert shuffled.tolist() == _expected.tolist(), f\"shuffled: {shuffled} — seed(0) y permutation(10)\"\nassert test_idx.tolist() == _expected[:2].tolist(), f\"test_idx: {test_idx} — los primeros 2 del barajado\"\nassert train_idx.tolist() == _expected[2:].tolist(), f\"train_idx: {train_idx}\"\nassert len(train_idx) == 8 and len(test_idx) == 2\nassert overlap == 0, f\"overlap: {overlap} — train y test JAMAS comparten indices\"",
      solution: "import numpy as np\n\nnp.random.seed(0)\n\nshuffled = np.random.permutation(10)\ntest_idx = shuffled[:2]\ntrain_idx = shuffled[2:]\noverlap = len(set(test_idx) & set(train_idx))",
      explanation: "<p>El truco de fondo: no se barajan los DATOS, se barajan los ÍNDICES. <code>permutation(10)</code> produce los números 0-9 en orden aleatorio, y el slicing los reparte: un corte limpio sin elementos repetidos ni perdidos — la verificación con sets (overlap 0) lo certifica, y certificarlo no es paranoia: el <em>data leakage</em> (datos de test filtrados al train) es el error silencioso más común y más caro del ML práctico; los papers se retractan por esto.</p><p>¿Por qué índices y no los datos directamente? Porque el mismo par train_idx/test_idx va a repartir COHERENTEMENTE a x y a y (y a cualquier otra columna): la receta de fancy indexing de NumPy — calcular índices una vez, aplicarlos a arrays paralelos — otra vez, ahora con propósito estadístico.</p>",
      hints: ["np.random.permutation(10) baraja los índices 0-9.", "test_idx = shuffled[:2], train_idx = shuffled[2:] — slicing del barajado.", "overlap: len(set(test_idx) & set(train_idx))."]
    },
    {
      id: "ml-split-2",
      title: "La función train_test_split",
      difficulty: 2,
      prompt: "<p>Empaquetá la mecánica en LA función (sí, la misma que scikit-learn trae con este nombre):</p><pre>def train_test_split(x, y, test_ratio=0.25, seed=0):\n    # devuelve x_train, x_test, y_train, y_test</pre><ol><li>Semilla, permutación de <code>len(x)</code> índices</li><li><code>n_test = int(len(x) * test_ratio)</code></li><li>Repartí los índices y usalos con fancy indexing sobre AMBOS arrays — el mismo barajado para x e y, o las parejas se desarman</li><li>Devolvé los cuatro en el orden del contrato</li></ol><p>Probala con los datos del starter e imprimí las shapes resultantes.</p>",
      starter: "import numpy as np\n\ndef train_test_split(x, y, test_ratio=0.25, seed=0):\n    pass\n\n# datos de prueba\nxs = np.arange(20) * 1.0\nys = xs * 2 + 1\n\nx_train, x_test, y_train, y_test = train_test_split(xs, ys)\n# print(x_train.shape, x_test.shape)\n",
      tests: "import numpy as _np\nassert len(x_test) == 5 and len(x_train) == 15, f\"con ratio 0.25 sobre 20: 15 train, 5 test — dio {len(x_train)}/{len(x_test)}\"\nassert len(y_test) == 5 and len(y_train) == 15\nfor _xv, _yv in zip(x_test, y_test):\n    assert abs(_yv - (_xv * 2 + 1)) < 1e-9, \"las parejas (x, y) se desarmaron: usa LOS MISMOS indices para ambos arrays\"\nfor _xv, _yv in zip(x_train, y_train):\n    assert abs(_yv - (_xv * 2 + 1)) < 1e-9, \"parejas rotas en train\"\nassert set(x_train.tolist()) | set(x_test.tolist()) == set(xs.tolist()), \"train + test deben cubrir TODOS los datos\"\nassert len(set(x_train.tolist()) & set(x_test.tolist())) == 0, \"sin solapamiento\"\n_a = train_test_split(xs, ys, seed=7)\n_b = train_test_split(xs, ys, seed=7)\nassert _np.allclose(_a[1], _b[1]), \"misma semilla, mismo split: reproducibilidad\"\n_c = train_test_split(xs, ys, seed=8)\nassert not _np.allclose(_a[1], _c[1]), \"semillas distintas deberian dar splits distintos\"",
      solution: "import numpy as np\n\ndef train_test_split(x, y, test_ratio=0.25, seed=0):\n    np.random.seed(seed)\n    indices = np.random.permutation(len(x))\n    n_test = int(len(x) * test_ratio)\n    test_idx = indices[:n_test]\n    train_idx = indices[n_test:]\n    return x[train_idx], x[test_idx], y[train_idx], y[test_idx]\n\nxs = np.arange(20) * 1.0\nys = xs * 2 + 1\n\nx_train, x_test, y_train, y_test = train_test_split(xs, ys)",
      explanation: "<p>El test más importante era el de las parejas: cada (x, y) de test debía seguir cumpliendo y = 2x + 1 — la prueba de que barajaste los índices UNA vez y los aplicaste a ambos arrays. El bug alternativo (permutar x e y por separado) desarma las parejas y entrena con basura… sin tirar un solo error. En ML, los bugs no explotan: degradan en silencio — por eso esta clase de verificaciones estructurales (parejas intactas, sin overlap, cobertura total) valen más que mil prints.</p><p>La firma — defaults razonables, semilla configurable, retorno de 4 en orden fijo — es deliberadamente la de scikit-learn: cuando mañana escribas <code>from sklearn.model_selection import train_test_split</code>, vas a saber exactamente qué hay adentro, porque lo escribiste.</p>",
      hints: ["Adentro: seed → permutation(len(x)) → n_test = int(len(x) * ratio) → repartir índices → indexar AMBOS arrays con los mismos índices.", "return x[train_idx], x[test_idx], y[train_idx], y[test_idx] — ese orden.", "¿Parejas rotas según el test? Estás permutando x e y por separado."]
    },
    {
      id: "ml-split-3",
      title: "Entrenar acá, examinar allá",
      difficulty: 3,
      prompt: "<p>El protocolo completo por primera vez. Con el dataset de siempre (en el starter) y tu split:</p><ol><li>Partí 75/25 (<code>test_ratio=0.25, seed=0</code>)</li><li>Ajustá la fórmula cerrada usando <strong>SOLO x_train, y_train</strong> → <code>w_hat</code>, <code>b_hat</code>. El test set no se toca durante el entrenamiento: ni una media, ni un vistazo.</li><li><code>train_mse</code>: el error sobre lo que vio; <code>test_mse</code>: el error sobre lo que NUNCA vio</li><li>Imprimí ambos y compará: ¿cuánto difieren? ¿El modelo generaliza?</li></ol>",
      starter: "import numpy as np\n\nnp.random.seed(42)\nx = np.random.rand(80) * 10\ny = 2.5 * x + 10 + np.random.randn(80)\n\ndef train_test_split(x, y, test_ratio=0.25, seed=0):\n    np.random.seed(seed)\n    indices = np.random.permutation(len(x))\n    n_test = int(len(x) * test_ratio)\n    return x[indices[n_test:]], x[indices[:n_test]], y[indices[n_test:]], y[indices[:n_test]]\n\ndef mse(y_true, y_pred):\n    return ((y_true - y_pred) ** 2).mean()\n\n# 1. split\n# 2. w_hat, b_hat con SOLO los datos de train\n# 3. train_mse, test_mse\n# print(train_mse, test_mse)\n",
      tests: "assert len(x_train) == 60 and len(x_test) == 20, f\"split 75/25 de 80: 60/20 — dio {len(x_train)}/{len(x_test)}\"\nimport numpy as _np\n_xm, _ym = x_train.mean(), y_train.mean()\n_w = ((x_train - _xm) * (y_train - _ym)).mean() / ((x_train - _xm) ** 2).mean()\n_b = _ym - _w * _xm\nassert abs(w_hat - _w) < 1e-9, f\"w_hat: {w_hat} — la formula debe usar SOLO x_train/y_train\"\nassert abs(b_hat - _b) < 1e-9, f\"b_hat: {b_hat}\"\nassert 2.2 < w_hat < 2.8 and 8.5 < b_hat < 11.5, f\"parametros: w={w_hat}, b={b_hat}\"\nassert train_mse < 2.0 and test_mse < 2.5, f\"train_mse={train_mse}, test_mse={test_mse} — ambos cerca del piso del ruido\"",
      solution: "import numpy as np\n\nnp.random.seed(42)\nx = np.random.rand(80) * 10\ny = 2.5 * x + 10 + np.random.randn(80)\n\ndef train_test_split(x, y, test_ratio=0.25, seed=0):\n    np.random.seed(seed)\n    indices = np.random.permutation(len(x))\n    n_test = int(len(x) * test_ratio)\n    return x[indices[n_test:]], x[indices[:n_test]], y[indices[n_test:]], y[indices[:n_test]]\n\ndef mse(y_true, y_pred):\n    return ((y_true - y_pred) ** 2).mean()\n\nx_train, x_test, y_train, y_test = train_test_split(x, y)\n\nxm, ym = x_train.mean(), y_train.mean()\nw_hat = ((x_train - xm) * (y_train - ym)).mean() / ((x_train - xm) ** 2).mean()\nb_hat = ym - w_hat * xm\n\ntrain_mse = mse(y_train, w_hat * x_train + b_hat)\ntest_mse = mse(y_test, w_hat * x_test + b_hat)",
      explanation: "<p>Los dos números que imprimiste cuentan una linda historia: parecidos entre sí y ambos cerca del piso del ruido (~1). Lectura: el modelo rinde EN LO NUEVO casi igual que en lo conocido → <strong>generalizó</strong>. Y tiene sentido que así sea: una recta de 2 parámetros no tiene memoria suficiente para memorizar 60 puntos — su única opción era aprender el patrón. (Adelanto: el próximo ejercicio te muestra el caso contrario, y la brecha train/test gritando.)</p><p>El detalle de disciplina que los tests vigilaron: la media, la covarianza, TODO se calculó sobre train. Hasta un inocente <code>x.mean()</code> sobre el dataset completo es leakage — información del test filtrándose al entrenamiento. La regla profesional es brutal y simple: <em>el test set está en una caja fuerte; se abre una vez, al final, para el número que va al informe.</em></p>",
      hints: ["El split ya está en el starter: x_train, x_test, y_train, y_test = train_test_split(x, y).", "La fórmula cerrada del tema anterior, pero CADA aparición de x o y es x_train o y_train.", "train_mse evalúa sobre train; test_mse, sobre test — mismo w_hat y b_hat en ambas."]
    },
    {
      id: "ml-split-4",
      title: "El loro vs la recta: overfitting en vivo",
      difficulty: 4,
      prompt: "<p>Construí el modelo memorizador del modo socrático y mirá cómo el split lo desenmascara:</p><ol><li><code>predict_memo(x_query, x_train, y_train)</code>: para UN x consultado, encontrá el índice del x_train más cercano (<code>np.argmin(np.abs(x_train - x_query))</code>) y devolvé SU y_train. El loro: no aprende, busca.</li><li><code>memo_train_preds</code>: la predicción del loro para CADA punto de train (un loop o comprehension sobre x_train, convertido a array) → <code>memo_train_mse</code> = <strong>0.0 exacto</strong> (¿por qué? cada punto se encuentra a sí mismo)</li><li><code>memo_test_preds</code> y <code>memo_test_mse</code>: el examen real, sobre x_test</li><li><code>gap_check</code>: ¿el loro rinde PEOR en test que la recta del ejercicio anterior? <code>memo_test_mse &gt; linear_test_mse</code> (la recta ya está calculada en el starter)</li></ol>",
      starter: "import numpy as np\n\nnp.random.seed(42)\nx = np.random.rand(80) * 10\ny = 2.5 * x + 10 + np.random.randn(80)\n\nnp.random.seed(0)\n_idx = np.random.permutation(80)\nx_train, x_test = x[_idx[20:]], x[_idx[:20]]\ny_train, y_test = y[_idx[20:]], y[_idx[:20]]\n\ndef mse(y_true, y_pred):\n    return ((y_true - y_pred) ** 2).mean()\n\n# la recta, ya entrenada en train (referencia):\n_xm, _ym = x_train.mean(), y_train.mean()\n_w = ((x_train - _xm) * (y_train - _ym)).mean() / ((x_train - _xm) ** 2).mean()\n_b = _ym - _w * _xm\nlinear_test_mse = mse(y_test, _w * x_test + _b)\n\ndef predict_memo(x_query, x_train, y_train):\n    pass\n\n# memo_train_preds, memo_train_mse = ?\n# memo_test_preds, memo_test_mse = ?\n# gap_check = ?\n# print(\"memo train:\", memo_train_mse, \"| memo test:\", memo_test_mse, \"| recta test:\", linear_test_mse)\n",
      tests: "import numpy as _np\nassert abs(predict_memo(x_train[0], x_train, y_train) - y_train[0]) < 1e-12, \"consultar un punto DE train debe devolver SU propio y\"\nassert memo_train_mse < 1e-12, f\"memo_train_mse: {memo_train_mse} — el loro clava CERO en lo que memorizo\"\nassert memo_test_mse > 0.5, f\"memo_test_mse: {memo_test_mse} — en lo nuevo, el loro paga su falta de patron\"\nassert bool(gap_check) is True, f\"el loro (test {memo_test_mse:.2f}) deberia perder contra la recta (test {linear_test_mse:.2f})\"",
      solution: "import numpy as np\n\n# (datos y recta de referencia como en el starter)\n\ndef predict_memo(x_query, x_train, y_train):\n    nearest = np.argmin(np.abs(x_train - x_query))\n    return y_train[nearest]\n\nmemo_train_preds = np.array([predict_memo(q, x_train, y_train) for q in x_train])\nmemo_train_mse = mse(y_train, memo_train_preds)\n\nmemo_test_preds = np.array([predict_memo(q, x_train, y_train) for q in x_test])\nmemo_test_mse = mse(y_test, memo_test_preds)\n\ngap_check = memo_test_mse > linear_test_mse",
      explanation: "<p>Los tres números que imprimiste son la lección más importante de todo el curso de ML:</p><p><strong>Loro en train: 0.000</strong> — perfección absoluta. Si solo miraras este número, dirías \"modelo increíble, a producción\". <strong>Loro en test: ~2</strong> — el doble de error que la recta (~1). La perfección era memoria: ante un x nuevo, el loro devuelve el y de OTRO punto, arrastrando su ruido — de hecho su error en test es ~2 porque suma DOS ruidos: el del punto consultado y el del vecino copiado. <strong>La recta: ~1 en ambos</strong> — nunca fue perfecta en train (no puede memorizar con 2 parámetros) pero destiló el patrón, y el patrón viaja a los datos nuevos.</p><p>Eso es <em>overfitting</em>: la brecha train↔test como síntoma, la capacidad de memorizar como causa. Y la moraleja operativa que ya nunca te va a abandonar: <strong>el error de entrenamiento no es evidencia de nada</strong> — solo el test set, virgen y bien separado, dice la verdad. (Tu loro, dicho con respeto, es el algoritmo 1-nearest-neighbor: con k vecinos y votación se vuelve respetable — próximo ejercicio.)</p>",
      hints: ["predict_memo: nearest = np.argmin(np.abs(x_train - x_query)); return y_train[nearest].", "Las predicciones masivas: np.array([predict_memo(q, x_train, y_train) for q in x_test]).", "gap_check = memo_test_mse > linear_test_mse — debería dar True con margen."]
    },
    {
      id: "ml-split-5",
      title: "kNN: tu primer clasificador",
      difficulty: 5,
      prompt: "<p>Del loro al clasificador serio: <strong>k-nearest neighbors</strong>. El starter genera dos nubes de puntos 2D (clase 0 y clase 1). Implementá:</p><ol><li><code>predict_knn(point, X, y, k=3)</code>: distancias euclidianas de <code>point</code> a TODOS los puntos (<code>np.linalg.norm(X - point, axis=1)</code> — broadcasting de (40,2) menos (2,)), índices de los k más cercanos (<code>argsort</code> + slice), y votación: la clase mayoritaria entre esos k — para etiquetas 0/1, <code>int(round(media de los votos))</code>.</li><li><code>pred_origin</code>: la clase predicha para <code>[0, 0]</code> (centro de la nube 0) y <code>pred_far</code>: para <code>[4, 4]</code> (centro de la 1)</li><li><code>all_preds</code>: la predicción para CADA punto del dataset (comprehension + array)</li><li><code>accuracy</code>: la fracción de aciertos — el idiom <code>(all_preds == y).mean()</code> → debería dar ≈ 1.0 (las nubes están bien separadas)</li></ol>",
      starter: "import numpy as np\n\nnp.random.seed(7)\ncloud0 = np.random.randn(20, 2)          # clase 0, centrada en (0,0)\ncloud1 = np.random.randn(20, 2) + 4      # clase 1, centrada en (4,4)\nX = np.vstack((cloud0, cloud1))           # (40, 2)\ny = np.array([0] * 20 + [1] * 20)\n\ndef predict_knn(point, X, y, k=3):\n    pass\n\n# pred_origin = ?\n# pred_far = ?\n# all_preds = ?\n# accuracy = ?\n",
      tests: "import numpy as _np\nassert predict_knn(_np.array([0.0, 0.0]), X, y) == 0, \"el origen pertenece a la nube 0\"\nassert predict_knn(_np.array([4.0, 4.0]), X, y) == 1, \"(4,4) pertenece a la nube 1\"\nassert pred_origin == 0 and pred_far == 1, f\"pred_origin={pred_origin}, pred_far={pred_far}\"\nassert isinstance(predict_knn(_np.array([2.0, 2.0]), X, y), int), \"la prediccion debe ser un int (0 o 1)\"\nassert len(all_preds) == 40, f\"all_preds: una prediccion por punto ({len(all_preds)})\"\nassert accuracy >= 0.95, f\"accuracy: {accuracy} — con nubes tan separadas, kNN deberia rozar el 100%\"",
      solution: "import numpy as np\n\nnp.random.seed(7)\ncloud0 = np.random.randn(20, 2)\ncloud1 = np.random.randn(20, 2) + 4\nX = np.vstack((cloud0, cloud1))\ny = np.array([0] * 20 + [1] * 20)\n\ndef predict_knn(point, X, y, k=3):\n    distances = np.linalg.norm(X - point, axis=1)\n    nearest = np.argsort(distances)[:k]\n    votes = y[nearest]\n    return int(round(votes.mean()))\n\npred_origin = predict_knn(np.array([0.0, 0.0]), X, y)\npred_far = predict_knn(np.array([4.0, 4.0]), X, y)\n\nall_preds = np.array([predict_knn(p, X, y) for p in X])\naccuracy = (all_preds == y).mean()",
      explanation: "<p>Cuatro líneas de cuerpo y es un clasificador real — desarmemos por qué cada una te resultó familiar:</p><p><code>norm(X - point, axis=1)</code>: broadcasting (40,2)−(2,) + la norma del nivel NumPy = 40 distancias de un golpe, sin loop. <code>argsort(...)[:k]</code>: tu pipeline de \"top-k\" de indexing, aplicado a cercanía. <code>y[nearest]</code>: fancy indexing — los índices calculados en el espacio de distancias, cosechando en el array de etiquetas. La votación con <code>round(mean)</code>: para 0s y 1s, la media &gt; 0.5 significa mayoría de 1s — el truco del accuracy, invertido.</p><p>Y la idea de fondo de kNN, digna de filosofía barata pero efectiva: \"sos parecido a tus vecinos\". Sin entrenamiento (los datos SON el modelo — como el loro, pero la votación entre k vecinos promedia el ruido que al loro lo hundía), funciona sorprendentemente bien en mil problemas, y es EL baseline serio de clasificación.</p><p>Mirá el camino recorrido: hace cinco niveles no sabías qué era una variable; acabás de implementar, desde cero y entendiendo cada línea, un algoritmo que se usa en producción. El proyecto final te espera.</p>",
      hints: ["Las cuatro líneas: distancias (norm con axis=1), nearest (argsort + [:k]), votos (y[nearest]), retorno (int(round(votes.mean()))).", "X - point broadcastea la resta a las 40 filas — no hace falta loop para las distancias.", "all_preds: np.array([predict_knn(p, X, y) for p in X]). accuracy: (all_preds == y).mean()."]
    }
  ]
},

/* ---------------- PROYECTO ML ---------------- */
{
  id: "proyecto-ml",
  title: "Proyecto: Pipeline de ML completo",
  isProject: true,
  intro: "El examen final del dojo: un pipeline de machine learning de punta a punta — datos, split, entrenamiento, evaluación honesta contra baseline, y predicción para un caso nuevo. Todo lo que aprendiste, en el orden en que se usa profesionalmente.",
  socratic: [
    {
      q: "Repasá el orden del pipeline: generar/cargar datos → split → entrenar → evaluar → predecir. ¿Por qué el split va ANTES de entrenar y no después?",
      a: "Porque todo lo que el entrenamiento toca queda \"contaminado\" como evidencia: si entrenás con el 100% y después separás, el test ya fue visto y su veredicto no vale nada. El split es lo PRIMERO que se hace tras cargar los datos — antes de normalizar, antes de mirar estadísticas, antes de todo — y el test va a la caja fuerte. En proyectos reales este orden es ley: hasta las medias para normalizar se calculan solo sobre train."
    },
    {
      q: "El proyecto te pide ganarle al baseline de la media. Si tu regresión NO le ganara, ¿qué tres causas sospecharías, en orden?",
      a: "(1) Bug en el código — el sospechoso de siempre: parejas x/y desarmadas en el split, fórmula con un signo dado vuelta, evaluar con los parámetros equivocados. (2) No hay relación lineal entre la feature y el target — el modelo correcto para una relación que no existe pierde contra la media. (3) Fuga de varianza: el target depende de factores que tu feature no captura. El orden importa: el 90% de las veces es la causa 1 — por eso el pipeline se construye con verificaciones en cada paso, como hiciste todo el curso."
    },
    {
      q: "Tu modelo va a predecir el precio de una casa de 100 m² que no existe en los datos. ¿Qué te da derecho a confiar en ese número?",
      a: "Tres evidencias que tu pipeline produce: el test MSE (rinde bien en datos que no vio — generaliza), la paliza al baseline (aprendió señal real, no ruido), y que 100 m² está DENTRO del rango de los datos de entrenamiento (interpolación). La tercera es la trampa clásica: el mismo modelo prediciendo para 10.000 m² extrapolaría fuera de todo lo visto, y ninguna métrica de test te protege ahí. Un modelo es confiable EN el territorio que conoció."
    }
  ],
  exercises: [
    {
      id: "ml-proj-1",
      title: "Pipeline completo: tasador de casas",
      difficulty: 5,
      prompt: "<p>La inmobiliaria del primer ejercicio del nivel vuelve — pero ahora los parámetros van a salir de los datos. El starter genera 100 casas reales-ish (superficie 30-180 m², precio = 1800·área + 25000 + ruido). Implementá el pipeline:</p><ol><li><code>train_test_split(x, y, test_ratio=0.2, seed=0)</code> — tu función de siempre → 80 train / 20 test</li><li><code>fit_linear(x, y)</code> → <code>(w, b)</code> por fórmula cerrada</li><li><code>predict(x, w, b)</code> y <code>mse(y_true, y_pred)</code></li><li>Ejecutá: entrená en train → <code>w</code>, <code>b</code>; evaluá → <code>train_mse</code>, <code>test_mse</code></li><li><code>baseline_mse</code>: el MSE en TEST de predecir siempre <code>y_train.mean()</code> (la media DE TRAIN: el test no aporta ni su media) y <code>beats_baseline</code>: booleano</li><li><code>new_price</code>: el precio predicho para una casa de 100 m²</li></ol><p>Imprimí el reporte final: parámetros, los tres MSE y la tasación. Cuando los tests pasen: terminaste el dojo.</p>",
      starter: "import numpy as np\n\nnp.random.seed(3)\narea = np.random.rand(100) * 150 + 30      # 30 a 180 m2\nprice = 1800 * area + 25000 + np.random.randn(100) * 15000\n\ndef train_test_split(x, y, test_ratio=0.2, seed=0):\n    pass\n\ndef fit_linear(x, y):\n    pass\n\ndef predict(x, w, b):\n    pass\n\ndef mse(y_true, y_pred):\n    pass\n\n# pipeline:\n# x_train, x_test, y_train, y_test = ?\n# w, b = ?\n# train_mse, test_mse = ?\n# baseline_mse, beats_baseline = ?\n# new_price = ?\n\n# print(f\"w={w:.1f}  b={b:.0f}\")\n# print(f\"train={train_mse:.2e}  test={test_mse:.2e}  baseline={baseline_mse:.2e}\")\n# print(f\"casa de 100 m2: ${new_price:,.0f}\")\n",
      tests: "import numpy as _np\nassert len(x_train) == 80 and len(x_test) == 20, f\"split 80/20: {len(x_train)}/{len(x_test)}\"\nassert len(set(x_train.tolist()) & set(x_test.tolist())) == 0, \"sin solapamiento train/test\"\nfor _xv, _yv in zip(x_test[:5], y_test[:5]):\n    _i = _np.argmin(_np.abs(area - _xv))\n    assert abs(price[_i] - _yv) < 1e-6, \"las parejas (area, precio) se desarmaron en el split\"\nassert 1600 < w < 2000, f\"w: {w} — deberia rondar 1800 (el precio real por m2)\"\nassert -5000 < b < 55000, f\"b: {b} — deberia rondar 25000\"\nassert train_mse < 6e8 and test_mse < 6e8, f\"train={train_mse:.2e}, test={test_mse:.2e} — el ruido tiene std 15000, el MSE ronda 2.25e8\"\nassert test_mse > 1e7, \"un test MSE sospechosamente perfecto suele ser un bug (o leakage)\"\nassert abs(baseline_mse - mse(y_test, _np.full(20, y_train.mean()))) < 1e-3, \"baseline: predecir y_train.mean() para todo el test\"\nassert bool(beats_baseline) is True, f\"el modelo ({test_mse:.2e}) debe aplastar al baseline ({baseline_mse:.2e})\"\nassert baseline_mse / test_mse > 5, \"la mejora sobre baseline deberia ser de varias veces\"\nassert 185000 < new_price < 225000, f\"new_price: {new_price:.0f} — una casa de 100 m2 ronda los $205.000\"",
      solution: "import numpy as np\n\nnp.random.seed(3)\narea = np.random.rand(100) * 150 + 30\nprice = 1800 * area + 25000 + np.random.randn(100) * 15000\n\ndef train_test_split(x, y, test_ratio=0.2, seed=0):\n    np.random.seed(seed)\n    indices = np.random.permutation(len(x))\n    n_test = int(len(x) * test_ratio)\n    return x[indices[n_test:]], x[indices[:n_test]], y[indices[n_test:]], y[indices[:n_test]]\n\ndef fit_linear(x, y):\n    xm, ym = x.mean(), y.mean()\n    w = ((x - xm) * (y - ym)).mean() / ((x - xm) ** 2).mean()\n    b = ym - w * xm\n    return w, b\n\ndef predict(x, w, b):\n    return w * x + b\n\ndef mse(y_true, y_pred):\n    return ((y_true - y_pred) ** 2).mean()\n\nx_train, x_test, y_train, y_test = train_test_split(area, price)\n\nw, b = fit_linear(x_train, y_train)\n\ntrain_mse = mse(y_train, predict(x_train, w, b))\ntest_mse = mse(y_test, predict(x_test, w, b))\n\nbaseline_mse = mse(y_test, np.full(len(y_test), y_train.mean()))\nbeats_baseline = test_mse < baseline_mse\n\nnew_price = predict(100, w, b)\n\nprint(f\"w={w:.1f}  b={b:.0f}\")\nprint(f\"train={train_mse:.2e}  test={test_mse:.2e}  baseline={baseline_mse:.2e}\")\nprint(f\"casa de 100 m2: ${new_price:,.0f}\")",
      explanation: "<p>Tu reporte final cuenta la historia completa: <strong>w ≈ 1800</strong> — el modelo redescubrió el precio por metro cuadrado desde datos ruidosos, sin que nadie se lo dijera (compará con el primer ejercicio del nivel, donde el 1200 era un invento de la inmobiliaria). <strong>train ≈ test ≈ 2×10⁸</strong> — sin brecha: generaliza; y ese número ES el piso del ruido (std 15000 → varianza 2.25×10⁸): el modelo extrajo TODA la señal extraíble. <strong>baseline ~30 veces peor</strong> — la señal aprendida es real y enorme. <strong>$205.000 para 100 m²</strong> — interpolación en pleno territorio conocido: una predicción con derecho a existir.</p><p>Y el test antiparanoia que quizás te llamó la atención — \"un test MSE sospechosamente perfecto suele ser un bug\" — es una lección de cultura: en ML, los resultados demasiado buenos se investigan con MÁS dureza que los malos. Casi siempre son leakage.</p><p><strong>Mirá el inventario de lo que usaste sin pensarlo</strong>: funciones con defaults (Básico), unpacking y tuplas (Básico), slicing e índices (NumPy), broadcasting (NumPy), permutaciones con semilla (Intermedio), composición de funciones puras cada una con su trabajo (todo el curso). Ese stack ES la base real: lo que sigue — scikit-learn, pandas, PyTorch — son estas mismas ideas con más caballos de fuerza. El dojo te entregó el cinturón: ahora a pelear con datos de verdad.</p>",
      hints: ["Las cuatro funciones ya las escribiste en ejercicios anteriores — reconstruilas de memoria primero, espiá después.", "El pipeline es secuencial: split → fit (SOLO train) → mse en ambos lados → baseline (media de TRAIN evaluada en test) → predict(100, w, b).", "baseline_mse: mse(y_test, np.full(len(y_test), y_train.mean())).", "Activá los print del starter: leer tu propio reporte es la mitad de la gracia."]
    }
  ]
}
]);
